### ISSUE TITLE
ssr-types@^4.0.0 not find...

### ISSUE THREAD

**Issue by zhangwinning** [ykfe/ssr#10]

**Comment by zhangwinning** [comment]
例子跑不通。。。

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/103335276-7a81ef00-4aaf-11eb-9119-a6287218a622.png)
@zhangwinning 用的是哪个源

**Comment by zhangyuang** [comment]
用yarn和npm吧，cnpm看了下确实还没同步过来

**Comment by zhangyuang** [comment]
可以重新安装试试，已经在cnpm手动同步
