### ISSUE TITLE
动态路由如何处理404情况?

### ISSUE THREAD

**Issue by masx200** [ykfe/ssr#100]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 google找答案而不是在这里。

## 详细描述你的问题

动态路由如何处理404情况?

https://doc.ssr-fc.com/docs/features$fetch

https://doc.ssr-fc.com/docs/features$feRoutes#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1

https://www.nextjs.cn/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

## 期望的结果

```ts
export async function getServerSideProps(context) {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {}, // will be passed to the page component as props
  }
}
```

**Comment by zhangyuang** [comment]
处理404的情况跟你路由是不是动态根本没有任何关系啊。。
http://doc.ssr-fc.com/docs/features$faq#404%20500%20%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86

**Comment by masx200** [comment]
举个例子是这样的动态路由
动态路由即携带参数的路由，例如 /user/:id 这种

/user/render$id.vue 映射为 /user/:id

然后在fetch函数里面查询数据库

如果根据id查询到不存在的话,怎样让它显示404页面,而不是当前组件

莫非要throw error?

**Comment by zhangyuang** [comment]
id查询不到这是跟你业务强相关啊
你可以在服务端判断查询不到就重定向到 404去，或者直接给页面添加标志去前端展示404组件

status:404是针对你请求没有对应的服务端路由
