### ISSUE TITLE
vue + tsx + css module 

### ISSUE THREAD

**Issue by simuusang** [ykfe/ssr#104]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 google找答案而不是在这里。

## 详细描述你的问题
在使 vue 3.0 在使用 tsx 语法时，我修改了配置开启了css module ，但是发现第三方库的类名也会被编译，请问有啥办法可以解决这个问题吗
```
 css: () => ({
    loaderOptions: {
      cssOptions: {
        // https://github.com/webpack-contrib/css-loader/tree/v1.0.1
        modules: {
          localIdentName: "[name]__[local]--[hash:base64:5]",
          exportLocalsConvention: "camelCaseOnly",
        },
        url: (url, resourcePath) => {
          // Don't handle `img.png` urls
          if (/\.(png|jpe?g|gif|svg|eot|ttf|woff|woff2)$/i.test(url)) {
            return false;
          }
          return true;
        },
      },
    },
  }),
```

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$faq#%E5%AF%B9%E6%89%80%E6%9C%89%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E4%BB%B6%E4%BD%BF%E7%94%A8%20css%20modules

**Comment by zhangyuang** [comment]
直接设置auto属性不为false就行了，hash生成规则框架会做并且跟vite场景的规则抹平

**Comment by zhangyuang** [comment]
确定安装的是最新依赖，最近的版本对css-loader有更新

**Comment by simuusang** [comment]
好的，谢谢
