### ISSUE TITLE
css中的字体文件在构建后未输出

### ISSUE THREAD

**Issue by zcgzxg** [ykfe/ssr#106]
## 详细描述你的问题
ssr-plugin-vue3从5.5.74升级到5.6.14后发现字体图标无法正常展示,后来发现打包的输出中没有输出对应字体文件

## 期望的结果
css中的字体文件可正常输出

## 当前使用的版本
5,6.14

**Comment by zhangyuang** [comment]
给复现 and 字体等静态资源文件可以直接放在静态资源文件夹不需要webpack处理

**Comment by zcgzxg** [comment]
是node modules中的包里的css引用的字体文件

**Comment by zhangyuang** [comment]
发了一版新的，可以试试。主要是css-loader方面的

**Comment by zcgzxg** [comment]
可以了
