### ISSUE TITLE
引入antd-mobile后不支持按需引入样式

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#108]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 google找答案而不是在这里。

## 详细描述你的问题

使用`antd-mobile`后不支持引入样式，配置`babelExtraModule: [/module-name/]`也不生效
## 期望的结果
能按需`antd-mobile`的样式

## 当前使用的版本
```
    "@ant-design/icons": "^4.6.3",
    "@midwayjs/cache": "^2.12.7",
    "@midwayjs/decorator": "^2.12.3",
    "@midwayjs/swagger": "^1.0.7",
    "@midwayjs/web": "^2.12.7",
    "antd": "^4.16.12",
    "antd-mobile": "^2.3.4",
    "axios": "^0.21.1",
    "cache-manager": "^3.4.4",
    "egg": "^2.30.0",
    "egg-mysql": "^3.0.0",
    "egg-scripts": "^2.14.0",
    "mysql": "^2.18.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "ssr-core-react": "^5.6.5",
    "ssr-types-react": "^5.6.4",
```

**Comment by zhangyuang** [comment]
根目录创建 `babel.config.js`，并写入如下内容

```js

module.exports = { 
    "plugins": [ 
        ["import", { 
            "libraryName": "antd-mobile", 
             "libraryDirectory": 'lib',
            "style": true 
        }, 'antd-mobile'] 
    ] 
} 
```

**Comment by wuyiifan** [comment]
> 根目录创建 `babel.config.js`，并写入如下内容
> 
> ```js
> module.exports = { 
>     "plugins": [ 
>         ["import", { 
>             "libraryName": "antd-mobile", 
>              "libraryDirectory": 'lib',
>             "style": true 
>         }, 'antd-mobile'] 
>     ] 
> } 
> ```

非常感谢
