### ISSUE TITLE
cssModule 配置不生效

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#115]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题

在`config.js`配置`cssModule`不生效
## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by wuyiifan** [comment]
```
postcss: {
          cssModules: {
            enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
            config: {
              namingPattern: 'module', // 转换模式，取值为 global/module
              generateScopedName: '[hash:base64:5]'
            }
          }
        }
````

**Comment by zhangyuang** [comment]
看文档用的css-loader版本

**Comment by wuyiifan** [comment]
`"version": "4.2.2"`

**Comment by zhangyuang** [comment]
那你就去看css-loader的文档啊。。
```js
module.exports = {
  css: () => {
    return {
      loaderOptions: {
        cssOptions: {
          modules: {
           localIdentName: xxx
          }
        }
      }
    }
  }
}

```
