### ISSUE TITLE
store log只能显示 updateContext

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#117]
## 详细描述你的问题

目前控制台的`store`日志只显示 `updateContext` 一种`action`的，其他类型的貌似没有做。
![image](https://user-images.githubusercontent.com/87987128/135256773-5276e853-7bc3-4622-850d-ffa79e8e00b5.png)

## 期望的结果

期望支持多种`action type`的日志 
## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
参考文档http://doc.ssr-fc.com/docs/features$communication
你可以自己在定义的store里面做。不需要框架来做
