### ISSUE TITLE
自定义framework之后，npm run prod 加载不到config

### ISSUE THREAD

**Issue by lljj-x** [ykfe/ssr#119]
## 详细描述你的问题
1. 使用 `npm init egg --type=framework` 初始化一个 framework 包 `egg-framework-test`
2. 在ssr项目中配置package.json，framework 为 egg-framework-test
3. npm run prod 会500，start 是正常启动

查看了错误日志发现获取不到 `config.keys` 

## 期望的结果
npm run prod 正常启动，获取config

## 当前使用的版本
5.6.26

## 复现仓库地址
https://github.com/lljj-x/ssr-project-report

`egg-framework-test` 这个通过cli初始化的一个framework 没做改动，发到了 npm

## 你本人对问题可能的原因判断(如果你能大概判断的话) 
查看日志文件 ~/logs/midway-vue-ssr/midway-vue-ssr-web.log 发现prod读取不到 config 

目前看到在 npm run start 使用 midway bin 去启动，prod 使用的egg scripts启动，猜测可能是一些dir配置问题

希望大佬可以指点下 。

**Comment by zhangyuang** [comment]
参考 https://cnodejs.org/topic/59102863d371b6372a8af6b4 ，去egg的issue找答案。

**Comment by lljj-x** [comment]
好嘞 多谢

**Comment by lljj-x** [comment]
找到问题了，egg-scripts 启动midway 项目必须 --framework=@midwayjs/web ，自己扩展的framework只需要配置 egg.framework
