### ISSUE TITLE
如何在非函数组件外向store存储数组

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#120]
## 详细描述你的问题
现在的场景是在token过期后直接在当前页面弹出登录框，获取到服务端的`401`状态来弹出登录。但是考虑此情景会在服务端和客户端发生。
目前想到的方案是：获取到`401状态后向store内存注入状态`，然后展示登录框。但是在非组件内向store注入数据貌似不可行。

你有什么好的解决方案么。

## 期望的结果
在组件外的环境里可以向`store`注入数据。

## 当前使用的版本
```
├─ ssr-client-utils@5.6.24
├─ ssr-core-react@5.6.25
├─ ssr-hoc-react@5.6.24
├─ ssr-plugin-midway@5.6.25
├─ ssr-plugin-react@5.6.25
├─ ssr-server-utils@5.6.25
├─ ssr-types-react@5.6.24
├─ ssr-types@5.6.24
├─ ssr-webpack@5.6.25
├─ ssr-window@3.0.0
├─ ssr@5.6.25
├─ ssri@7.1.1
└─ webpack@4.46.0
   └─ ssri@6.0.2
```
## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
这跟ssr没有任何关系。。是基础的react/vue问题。

如何在非函数组件外向store存储数组：不可以
token过期后直接在当前页面弹出登录框：有很多方案可以实现这个功能，自己多想想

**Comment by wuyiifan** [comment]
> 这跟ssr没有任何关系。。是基础的react/vue问题。
> 
> 如何在非函数组件外向store存储数组：不可以 token过期后直接在当前页面弹出登录框：有很多方案可以实现这个功能，自己多想想

想了半天没有好的思路。
大佬提供个思路呗

**Comment by zhangyuang** [comment]
弹窗组件控制自己的状态如果你是实时就用轮询/socket。不然就请求后自己去更新状态，最简单就是重定向到登陆页
