### ISSUE TITLE
服务端渲染报错 navigator is not defined

### ISSUE THREAD

**Issue by wyhooo** [ykfe/ssr#129]
## 详细描述你的问题

Vue@3.2.1  服务端渲染出错 `navigator is not defined`

## 期望的结果

正确渲染

## 当前使用的版本

5.6.28

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

https://github.com/vuejs/vue-next/blob/6916d725a06a57e92ff9d046ccf132c305cd0a51/packages/runtime-core/src/devtools.ts#L57

**Comment by zhangyuang** [comment]
已提pr等官方回复

**Comment by loyep** [comment]
目前建议 暂时锁定vue到3.2.19

**Comment by zhangyuang** [comment]
已修复
