### ISSUE TITLE
怎么验证腾讯视频和优酷视频用的是本框架，f12能看出来吗

### ISSUE THREAD

**Issue by show110695** [ykfe/ssr#134]
怎么验证腾讯视频和优酷视频用的是本框架，f12能看出来吗

**Comment by zhangyuang** [comment]
作者本人就是前优酷现腾讯员工

**Comment by zhangyuang** [comment]
看window属性
![image](https://user-images.githubusercontent.com/17424434/142197491-15de6510-301e-40be-9848-33310a6d3a17.png)
![image](https://user-images.githubusercontent.com/17424434/142197531-0a4a41d6-36d2-46ee-8cb1-6421ea1ca135.png)
