### ISSUE TITLE
拍信创意主要页面使用本框架渲染

### ISSUE THREAD

**Issue by lacoooo** [ykfe/ssr#139]
https://www.paixin.com

拍信创意logo：
 ![Image text](https://www.paixin.com/images/black-paixin-text.svg)

**Comment by zhangyuang** [comment]
感谢使用，可以提个pr加入到readme中

**Comment by zhangyuang** [comment]
Be added by https://github.com/zhangyuang/ssr/commit/bc75eb75d587b17ab964d918ae635413ace314a6
