### ISSUE TITLE
外部使用用户收集

### ISSUE THREAD

**Issue by zhangyuang** [ykfe/ssr#140]
若您的应用使用本框架进行开发可以提issue或者pr加入到readme当中，也可以直接在本issue下补充回复

**Comment by wizardpisces** [comment]
启动没问题，访问 _http://127.0.0.1:3000/_ 报错：

![image](https://user-images.githubusercontent.com/3377557/146504887-1e466623-0e67-4356-b029-7973f785961a.png)

**复现步骤：**

$ npm init ssr-app my-ssr-project
选择  midway-vue3-ssr
$ cd my-ssr-project
$ npm install
$ npm run start:vite
$ 访问 _http://127.0.0.1:3000/_ 

npm@6.14.15
node@v12.22.7

**Comment by zhangyuang** [comment]
> 启动没问题，访问 _http://127.0.0.1:3000/_ 报错：
> 
> ![image](https://user-images.githubusercontent.com/3377557/146504887-1e466623-0e67-4356-b029-7973f785961a.png)
> 
> **复现步骤：**
> 
> $ npm init ssr-app my-ssr-project 选择 midway-vue3-ssr $ cd my-ssr-project $ npm install $ npm run start:vite $ 访问 _http://127.0.0.1:3000/_
> 
> npm@6.14.15 node@v12.22.7

已知问题，临时解决方案升级node14，可以用nvm管理node版本

**Comment by wizardpisces** [comment]
好的感谢，这个会有长期方案修复的计划么

**Comment by zhangyuang** [comment]
如果你用react，现在就可以修复。vue3场景这里大概率是vite的问题导致的。需要研究下

**Comment by zhangyuang** [comment]
发现问题了，已修复，等会安装最新版本依赖即可

**Comment by wizardpisces** [comment]
修复的还挺快，具体是啥问题

**Comment by zhangyuang** [comment]
node12不支持optional chaining 需要额外处理

**Comment by zhangyuang** [comment]
最新版本已修复

**Comment by shaoyi-robin-zhou** [comment]
我是从原vite用户迁移过来的,然后要用windicss 的vite插件.在经过多次的调试后.  提两个建议,
1. 在vite模式下开放extraJsOrder,不然加载不了windicss.ts.
![lQLPDhsKnsd6wb85zQQesITqtDnotZHbAeISyPnAOAA_1054_57](https://user-images.githubusercontent.com/60779124/148712597-88d02d17-ad69-43d4-b4d6-4a763dd03242.png)
2.对原插件的使用方式应该类似这样的文档补充,或者代码适配.

 
` js
     const vitePluginWindicss =require("vite-plugin-windicss");

        let vitePluginW = vitePluginWindicss.default(windiConfig);
`

**Comment by zhangyuang** [comment]
不要在无关issue下回复建议新开issue
extrajsorder在vite场景下是开放的但是很明显不是用来解决你的问题的
默认配置无法实现功能的话有问题新开issue给复现



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: robin-zhou.cn ***@***.***&gt;
发送时间: 2022年1月10日 10:43
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 外部使用用户收集 (Issue #140)





 
我是从原vite用户迁移过来的,然后要用windicss 的vite插件.在经过多次的调试后.  提两个建议,
  
在vite模式下开放extraJsOrder,不然加载不了windicss.ts.
 
 2.对原插件的使用方式应该类似这样的文档补充,或者代码适配. 
 
` js
 const vitePluginWindicss =require("vite-plugin-windicss");
     let vitePluginW = vitePluginWindicss.default(windiConfig);  
`
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cyber-echo** [comment]
怎么获取vuex的实例，需要在非组件的js中dispatch

**Comment by zhangyuang** [comment]
自己拿到this.$store保存在对象中（不要在无关issue下提问



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo ***@***.***&gt;
发送时间: 2022年4月25日 20:19
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 外部使用用户收集 (Issue #140)





 
怎么获取vuex的实例，需要在非组件的js中dispatch

**Comment by pakkery** [comment]
怎么引入element-plus

**Comment by fmx1151** [comment]
ssr-common-utils 今天更新的版本使用报错
Error: Cannot find module '@vue/server-renderer/index.js'
Require stack:
- /usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js
- /usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js
- /usr/local/nano/sparkle-marketing/dist/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at loadModuleFromFramework (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js:292:20)
    at loadConfig (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/loadConfig.js:42:105)
    at Object.<anonymous> (/usr/local/nano/sparkle-marketing/node_modules/ssr-core/cjs/render.js:7:57)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js',
    '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js',
    '/usr/local/nano/sparkle-marketing/dist/main.js'
  ]
}

**Comment by zhangyuang** [comment]
删除lock安装最新版本试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fmx1151 ***@***.***&gt;
发送时间: 2024年2月21日 17:51
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 外部使用用户收集 (Issue #140)





 
ssr-common-utils 今天更新的版本使用报错
 Error: Cannot find module ***@***.***/server-renderer/index.js'
 Require stack:
  
/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js
 
/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js
 
/usr/local/nano/sparkle-marketing/dist/main.js
 at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
 at Function.resolve (node:internal/modules/cjs/helpers:125:19)
 at loadModuleFromFramework (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js:292:20)
 at loadConfig (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/loadConfig.js:42:105)
 at Object. (/usr/local/nano/sparkle-marketing/node_modules/ssr-core/cjs/render.js:7:57)
 at Module._compile (node:internal/modules/cjs/loader:1256:14)
 at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 at Module.load (node:internal/modules/cjs/loader:1119:32)
 at Module._load (node:internal/modules/cjs/loader:960:12)
 at Module.require (node:internal/modules/cjs/loader:1143:19) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [
 '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js',
 '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js',
 '/usr/local/nano/sparkle-marketing/dist/main.js'
 ]
 }

**Comment by epoll-j** [comment]
> ssr-common-utils 今天更新的版本使用报错 Error: Cannot find module '@vue/server-renderer/index.js' Require stack:
> 
> * /usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js
> * /usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js
> * /usr/local/nano/sparkle-marketing/dist/main.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Function.resolve (node:internal/modules/cjs/helpers:125:19)
>   at loadModuleFromFramework (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js:292:20)
>   at loadConfig (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/loadConfig.js:42:105)
>   at Object. (/usr/local/nano/sparkle-marketing/node_modules/ssr-core/cjs/render.js:7:57)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Module.require (node:internal/modules/cjs/loader:1143:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js',
>   '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js',
>   '/usr/local/nano/sparkle-marketing/dist/main.js'
>   ]
>   }

我有同样的问题，直接通过脚手架创建midway-react18-ssr的项目，运行就报这个错误了

**Comment by zhangyuang** [comment]
保证所有ssr的依赖版本都是最新的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dubhe ***@***.***&gt;
发送时间: 2024年2月29日 11:39
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 外部使用用户收集 (Issue #140)





  
ssr-common-utils 今天更新的版本使用报错 Error: Cannot find module ***@***.***/server-renderer/index.js' Require stack:
  
/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js
 
/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js
 
/usr/local/nano/sparkle-marketing/dist/main.js
 at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
 at Function.resolve (node:internal/modules/cjs/helpers:125:19)
 at loadModuleFromFramework (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js:292:20)
 at loadConfig (/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/loadConfig.js:42:105)
 at Object. (/usr/local/nano/sparkle-marketing/node_modules/ssr-core/cjs/render.js:7:57)
 at Module._compile (node:internal/modules/cjs/loader:1256:14)
 at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 at Module.load (node:internal/modules/cjs/loader:1119:32)
 at Module._load (node:internal/modules/cjs/loader:960:12)
 at Module.require (node:internal/modules/cjs/loader:1143:19) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [
 '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/cwd.js',
 '/usr/local/nano/sparkle-marketing/node_modules/ssr-common-utils/cjs/server/index.js',
 '/usr/local/nano/sparkle-marketing/dist/main.js'
 ]
 }
   
我有同样的问题，直接通过脚手架创建midway-react18-ssr的项目，运行就报这个错误了
