### ISSUE TITLE
有计划扩展第三方UI库的接入方式吗

### ISSUE THREAD

**Issue by itmanyong** [ykfe/ssr#141]
如题,例如想使用vue3的naive-ui，如果支持自定义扩展接入会很棒

**Comment by zhangyuang** [comment]
没懂你意思..看文档接入ui框架那一块

**Comment by itmanyong** [comment]
> 没懂你的英文。。看文档接入ui框架那一块

照着文档接入UI库说明，按着vant的解析撸了一遍naive-ui的接入。很遗憾没有成功！无法正确解析组件。~-~

**Comment by zhangyuang** [comment]
直接使用并没有任何问题，并且不推荐使用这些 css-in-js 方案的库样式会闪烁，直接用 antd/vant

```js
import { NButton } from 'naive-ui'
```
