### ISSUE TITLE
发布到腾讯云报Access Denied错误，我的账号只能访问特定的存储桶权限，是否支持配置上传的cos存储桶？

### ISSUE THREAD

**Issue by exdestroyer** [ykfe/ssr#143]
## 期望的结果
上传至特定的存储桶

## 当前使用的版本
6.0.0

**Comment by zhangyuang** [comment]
底层用的是midway，参考midway文档，不建议用腾讯云用阿里云

**Comment by loyep** [comment]
doc: [https://www.yuque.com/midwayjs/faas/serverless_yml](https://www.yuque.com/midwayjs/faas/serverless_yml)

**Comment by exdestroyer** [comment]
> 
在tx没法用阿里云啊
😂

**Comment by exdestroyer** [comment]
> 底层用的是midway，参考midway文档，不建议用腾讯云用阿里云

在tx没法用阿里云啊
😂
