### ISSUE TITLE
当我在macbook pro M1中的vscode终端中运行yarn start:vite会报错

### ISSUE THREAD

**Issue by xiaokyo** [ykfe/ssr#149]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题

报错如下
![image](https://user-images.githubusercontent.com/22857964/146507630-377fbc2d-e122-4e42-ac69-71b1f3430f2f.png)

## 期望的结果
不报错, 正常运行

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

![image](https://user-images.githubusercontent.com/22857964/146507824-9376d9be-d0f8-4d4b-8655-0486f802bac8.png)

## 复现仓库地址

npm init ssr-app my-ssr-project使用react midway创建出来的项目直接在vscode终端启动

**Comment by zhangyuang** [comment]
错误信息呢

**Comment by xiaokyo** [comment]
> 错误信息呢

贴了, 刚刚还在编辑

**Comment by zhangyuang** [comment]
重装依赖试试，也有可能是esbuild的问题，你的电脑是m1但是这里找不到的依赖是optional-dependencies在intel mac系统下才会安装使用的依赖。
可以单独跑vite脚手架创建的项目看看能否运行

**Comment by xiaokyo** [comment]
> 重装依赖试试，也有可能是esbuild的问题，你的电脑是m1但是这里找不到的依赖是optional-dependencies在intel mac系统下才会安装使用的依赖。 可以单独跑vite脚手架创建的项目看看能否运行

好的, 我试试

**Comment by zhangyuang** [comment]
用命令看看你的平台架构是多少
![image](https://user-images.githubusercontent.com/17424434/146510082-f1685c3c-93f5-46e1-82f9-52d312f8b095.png)

**Comment by xiaokyo** [comment]
> 用命令看看你的平台架构是多少 ![image](https://user-images.githubusercontent.com/17424434/146510082-f1685c3c-93f5-46e1-82f9-52d312f8b095.png)

![image](https://user-images.githubusercontent.com/22857964/147202877-2af3fd76-9cd7-4063-803b-c33fb1177fb7.png)

**Comment by zhangyuang** [comment]
那应该是依赖安装的问题，重装试试
