### ISSUE TITLE
文本节点渲染问题

### ISSUE THREAD

**Issue by simuusang** [ykfe/ssr#152]
## 详细描述你的问题
使用最新的 6.0.0 的框架时 vue 的文本节点渲染会抛出 warning 如下：
当采用如下方式书写则会报错
![image](https://user-images.githubusercontent.com/16282764/148905317-23f631cb-8d12-4786-8a08-e3cdb81b7f4e.png)

## 期望的结果
用模板字符串写他就正常，不报错
![image](https://user-images.githubusercontent.com/16282764/148905531-9ea6360d-24b0-43e2-978e-ed125fbf41da.png)

## 当前使用的版本

yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ ssr-client-utils@6.1.46
├─ ssr-core-vue3@6.1.46
├─ ssr-plugin-nestjs@6.1.46
├─ ssr-plugin-vue3@6.1.46
│  └─ ssri@7.1.1
├─ ssr-server-utils@6.1.46
├─ ssr-types@6.1.46
├─ ssr-webpack@6.1.46
├─ ssr-window@3.0.0
├─ ssr@6.1.46
└─ ssri@6.0.2
✨  Done in 0.81s.

**Comment by zhangyuang** [comment]
大概率是 vue3 自身的问题
