### ISSUE TITLE
配置core-js，页面报错

### ISSUE THREAD

**Issue by zpfZPFgithub** [ykfe/ssr#156]
## 问题描述
我当前的模式是midway-ssr-vue,在config.ts中增加配置：
corejs：true
执行 npm run start
出现：
![image](https://user-images.githubusercontent.com/4669628/150079553-137f0536-be5f-4413-bf3f-1e352955d205.png)
corejs升级到3.0版本。npm i core-js@3.6.4 -D，这时不报错了
执行：
npm run start，打开ie浏览器，报错
![image](https://user-images.githubusercontent.com/4669628/150075047-87cbe3dd-2dbd-40e1-88fc-0659d1fd0c10.png)
![image](https://user-images.githubusercontent.com/4669628/150075278-c6a10614-365a-4fe8-bed8-bdf42878a0d0.png)
确定是node_modules被exclude的原因，在config.ts配置：babelExtraModule: [/javascript-stringify/]
![image](https://user-images.githubusercontent.com/4669628/150075494-983ef68b-1fd1-4b17-9917-35d48cb4678d.png)
继续报错：
![image](https://user-images.githubusercontent.com/4669628/150080380-ef41fff9-9998-4b2f-b7fb-097a470b667d.png)
webpack-chain出现在代码里，很奇怪，继续exclude：
![image](https://user-images.githubusercontent.com/4669628/150080538-f380dd6b-5f21-4759-99bd-c5c938d4301d.png)

这个时候打开ie11，报的错不一样了
![image](https://user-images.githubusercontent.com/4669628/150080751-09ffd630-fcc6-4c47-bd93-dc7459a7e270.png)
根据经验，是core-js没有exclude导致的问题，修改打开node_modules/ssr-plugin-vue/base.js，
![image](https://user-images.githubusercontent.com/4669628/150081076-29981845-8411-4d99-92d1-7fc6d3ee2e19.png)
重新编译打开ie11，问题解决
## 当前版本
v6.1.48
## 期望结果

- webpack-chain模块不应该出现在浏览器模块中
- 配置nodejs：true后，不需要配置其它内容，ie应该正常显示

## 问题可能的原因判断
- corejs版本问题没有处理好
- babel-loader配置的exclude有问题，core-js没有排除在外

**Comment by zhangyuang** [comment]
用生产环境的结果去看，开发环境没有参考价值，close by https://github.com/zhangyuang/ssr/commit/503f3e618a8918fbd482267349059d743af75787

**Comment by zhangyuang** [comment]
生产环境没有webpack-chain

**Comment by zpfZPFgithub** [comment]
core-js的问题呢，babel-loader没有exclude掉core-js

**Comment by zhangyuang** [comment]
https://github.com/zhangyuang/ssr/commit/503f3e618a8918fbd482267349059d743af75787#diff-115ab4ffd300a5a47bee4bb33263ca5b531cdcd22e3c739d6b960136bd460b78L135

**Comment by zpfZPFgithub** [comment]
另外上面提到，core-js默认安装的版本是^2的版本，直接npm run build是会报错哦。建议框架core-js最外层是^3的版本。这样就不用额外的npm i core-js@3.6.4 -D了

**Comment by zpfZPFgithub** [comment]
> [503f3e6#diff-115ab4ffd300a5a47bee4bb33263ca5b531cdcd22e3c739d6b960136bd460b78L135](https://github.com/zhangyuang/ssr/commit/503f3e618a8918fbd482267349059d743af75787#diff-115ab4ffd300a5a47bee4bb33263ca5b531cdcd22e3c739d6b960136bd460b78L135)

这样修改后babelExtraModule配置就失效了，需要把node_modules排除掉哦
应该是这样：babelForExtraModule = module.add(babelExtraModule).end().exclude.add(/core-js/).end();

**Comment by zhangyuang** [comment]
> 另外上面提到，core-js默认安装的版本是^2的版本，直接npm run build是会报错哦。建议框架core-js最外层是^3的版本。这样就不用额外的npm i core-js@3.6.4 -D了

这里框架无法设置啊，哪个版本的依赖会被提升到最顶层本来就是不确定的
