### ISSUE TITLE
vite版本运行时(npm run start:vite)构建不成功

### ISSUE THREAD

**Issue by 350469960** [ykfe/ssr#162]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
vite版本运行时（npm run start:vite）构建不成功，vite版本打包构建是正常的

## 期望的结果
vite版本运行时构建成功

## 当前使用的版本
midway-vue3-ssr初始化版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址
https://gitlab.com/mansea/my-ssr-project

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
无法复现

**Comment by 350469960** [comment]
我这边node版本12.22.0，运行完，打开页面时报错

![image](https://user-images.githubusercontent.com/23090716/151319937-fe049207-4afb-4159-998b-ad2ba4f42433.png)

**Comment by 350469960** [comment]
运行npm run prod:vite是可以的，就是npm run start:vite报错，不是vite版本是没有问题

**Comment by zhangyuang** [comment]
换个node14版本试试呢

**Comment by zhangyuang** [comment]
nvm切换为12.22.0 我这边仍然没问题

**Comment by 350469960** [comment]
node >= 14.17.0版本可以
