### ISSUE TITLE
支持vue3 的element-plus吗

### ISSUE THREAD

**Issue by netangsoft** [ykfe/ssr#163]
请问支持vue3 的element-plus吗

**Comment by zhangyuang** [comment]
看faq写的很清楚



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: netangsoft ***@***.***&gt;
发送时间: 2022年2月5日 15:31
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 支持vue3 的element-plus吗 (Issue #163)





 
请问支持vue3 的element-plus吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by netangsoft** [comment]
faq只有element-ui，element-ui是vue2版本的
我想问的是可支持element-plus？

**Comment by zhangyuang** [comment]
faq连原理都写的很清楚了啊…



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: netangsoft ***@***.***&gt;
发送时间: 2022年2月5日 15:38
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 支持vue3 的element-plus吗 (Issue #163)





 
faq只有element-ui，element-ui是vue2版本的
 我想问的是可支持element-plus？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by netangsoft** [comment]
好的
