### ISSUE TITLE
antd 样式引用问题

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#164]
写了一个组件，组件使用了antd，主项目以dependencies形式引入，呈现时antd写的插件样式没有引入，展示异常。
后面组件里面改成这种方式引用antd插件
<img width="425" alt="image" src="https://user-images.githubusercontent.com/21193805/153976962-02f265f6-491b-4eaa-9ead-2a4e36dce297.png">
但页面访问时报错
<img width="435" alt="image" src="https://user-images.githubusercontent.com/21193805/153977335-1b3bca38-9101-4900-a674-bcc7622c4c6c.png">

请问该怎么解决这个情况！

版本：
"ssr": "6.1.59"
"@midwayjs/web": "2.14.6",
"antd": "4.18.6",

**Comment by zhangyuang** [comment]
提供复现仓库
