### ISSUE TITLE
在约定式路由基础上拓展自定义路由path

### ISSUE THREAD

**Issue by zpfZPFgithub** [ykfe/ssr#165]
## 详细描述你的问题
当前框架仅支持约定式路由和声明式路由。
很多场景是需要约定式路由+特殊的神明式路由，比如框架对“index映射为/”的特殊处理。
框架能否支持一些特殊的路由覆盖，用户可以自定义覆盖默认的路由配置，生成符合需求的路由配置文件。
比如说vue里，可以给某些路由提供alias别名或者覆盖部分路由配置，生成用户想要的ssr-temporary-routes.js文件

## 期望的结果
生成符合需求的ssr-temporary-routes.js文件，支持alias或者路由覆盖

**Comment by zhangyuang** [comment]
Fix by https://github.com/zhangyuang/ssr/commit/c2b548284f8683c266e6e858d6a9eb91cb72bc50
Ref: http://doc.ssr-fc.com/docs/features$feRoutes#%E4%BC%98%E5%85%88%E7%BA%A7%E8%A6%86%E7%9B%96
