### ISSUE TITLE
增加的内存一直驻留

### ISSUE THREAD

**Issue by lacoooo** [ykfe/ssr#169]
我下载了此项目，把example文件夹中的midway-vue3-ssr项目安装依赖并运行，未作任何修改。然后对它进行了简单的压力测试。
在请求完一次首页的时候，马上请求下一次。
1000次请求后，内存从200多MB大致涨到1095MB，但之后它并没有回落。
然后再次执行压测脚本，内存涨到大概1850MB，之后降到1739MB后不再回落。

const axios = require('axios')
let count = 1000
async function test() {
    if (count == 0) {
        return
    }
    await axios('http://localhost:3000')
    count -= 1
    test()
}
test()

**Comment by zhangyuang** [comment]
不要用dev环境压测没有任何意义

**Comment by zhangyuang** [comment]
run prod

**Comment by lacoooo** [comment]
prod测试后确定没有问题，我自有项目有内存驻留问题，把demo切回和我自己项目同样的版本测试，也没测出问题。所以应该是业务代码的bug。多谢
