### ISSUE TITLE
cr 

### ISSUE THREAD

**Issue by i5ting** [ykfe/ssr#17]
issues

- plugin-faas和plugin-midway分的不好
- plugin代码在哪里？别人如何扩展
-  "vue": "^2.0.0",??
- vite部分没有看到
- create-ssr-app集成没有
- example和其他地方不要过度强调midway，这个版本主导Serverless
- example里既有midway又有egg，依赖需要处理一下。
- 测试基本没有。只有jest配置。
- fePlugin命名不好

优点

```
const { midwayPlugin } = require('ssr-plugin-midway')
const { vuePlugin } = require('ssr-plugin-vue')

module.exports = {
  serverPlugin: midwayPlugin(),
  fePlugin: vuePlugin()
}
```

用起来确实简单很多。接下来plugin围绕扩展，还有很多工作要做。

**Comment by i5ting** [comment]
TODO：文档以svelte.dev为例，如何自己扩展和定义一个Serverless-side render

**Comment by zhangyuang** [comment]
mark 记录
> plugin-faas和plugin-midway分的不好

plugin-faas基于midway-faas
plugin-midway基于midway-web
目前来看虽然都是midway系的，在启动部署构建方面差别还是比较大。且一个需要 `f.yml` 文件存在。暂时分为独立的两个插件分别针对 serverless场景 和传统 Node.js 应用场景。后续跟 midway 团队沟通如何统一

> plugin代码在哪里？别人如何扩展

plugin仅用于本地开发阶段使用，生产环境不依赖 plugin。通过 config.js 扩展应用的一些功能。此 plugin 不像 webpack plugin 以及 umi plugin。我们支持单个服务端plugin与单个前端plugin 互相组合。不支持多个服务端plugin或者前端plugin互相组合。此处的plugin粒度较大，详细描述见readme

> "vue": "^2.0.0",??

目前的结构是 vue2+webpack, vue3+vite 后续完善，但工作量不确定，暂时不一起发布。
vite部分没有看到

> create-ssr-app集成没有

详情见 readme，通过 `npm init ssr-app <projectName> --template=xxx`  创建不同的 example
example和其他地方不要过度强调midway，这个版本主导Serverless
> example里既有midway又有egg，依赖需要处理一下。
这是 midway@2.0 的用法，midway@2.0 将midway作为上层框架，egg/koa/express 作为底层框架根据需要安装使用

> 测试基本没有。只有jest配置。

e2e 测试所有的 example 都有， jest单测在egg-react-ssr 这个项目都有，晚点可以迁移过来并更新

> fePlugin命名不好

待讨论

**Comment by i5ting** [comment]
fePlugin 改为 clientPlugin，跟serverPlugin对应
