### ISSUE TITLE
有打算换pnpm来管理包依赖吗？

### ISSUE THREAD

**Issue by abelshare** [ykfe/ssr#172]

**Comment by zhangyuang** [comment]
暂时没有这个打算。你可以自行在创建出来的example中使用pnpm,pnpm自身问题还有不少，况且底层框架例如midway本身也不支持pnpm

**Comment by zhangyuang** [comment]
暂时没这个打算。你在创建出来的example里面自己用pnpm就行了。不过midway不支持pnpm并且pnpm的问题还很多



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: abelshare ***@***.***&gt;
发送时间: 2022年3月14日 11:09
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 有打算换pnpm来管理包依赖吗？ (Issue #172)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
