### ISSUE TITLE
是否有整合tailwindcss的计划，相对less sass，tailwind表现更加优秀

### ISSUE THREAD

**Issue by abelshare** [ykfe/ssr#173]
https://tailwindcss.com/

**Comment by zhangyuang** [comment]
搜文档关键字



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: abelshare ***@***.***&gt;
发送时间: 2022年3月14日 12:16
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 是否有整合tailwindcss的计划，相对less sass，tailwind表现更加优秀 (Issue #173)





 
https://tailwindcss.com/
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
