### ISSUE TITLE
有考虑支持vue3.2吗

### ISSUE THREAD

**Issue by huangbh1024** [ykfe/ssr#177]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
有vue3版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hais-hbh ***@***.***&gt;
发送时间: 2022年4月1日 18:05
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 有考虑支持vue3.2吗 (Issue #177)





 
提问前请确认以下几点信息，否则你的问题将不会被解答
  
参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式 

确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案 

对应服务端框架的使用问题请去它们的官方文档找答案。例如 Midway, Nest.js 

如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭 

原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。 
 
详细描述你的问题
 
期望的结果
 
当前使用的版本
 
不要贴 package.json 用 yarn list "ssr*"  来查看版本。同时建议熟读semver 规则并且知道怎么安装最新依赖！
 
复现仓库地址
 
超过一行代码能描述的问题必须提供复现地址, 用默认的 example 给最简单的复现代码不要给包含着一堆业务代码的仓库
 
你本人对问题可能的原因判断(如果你能大概判断的话)

**Comment by huangbh1024** [comment]
> 

vue3版本用的是3.0，3不支持3.2的一些api

**Comment by zhangyuang** [comment]
…那明显版本号是^3啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hais-hbh ***@***.***&gt;
发送时间: 2022年4月1日 18:11
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 有考虑支持vue3.2吗 (Issue #177)





   
vue3版本用的是3.0，3不支持3.2的一些api

**Comment by zhangyuang** [comment]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/17424434/161247376-9d913169-2dba-4cde-bec3-7ce4f0ec181c.png">
