### ISSUE TITLE
请问，midway-react-ssr 是否支持midway函数式一体化的方式开发

### ISSUE THREAD

**Issue by sinianzhiren** [ykfe/ssr#178]
请问，midway-react-ssr 是否支持midway函数式一体化的方式开发，有小伙伴试过吗，我看到 官方提供的demo是midway 的标准模式

**Comment by zhangyuang** [comment]
不支持 midway一体化包含他们自定义的构建逻辑和启动逻辑。跟ssr冲突，后续看看我们是否提供自己的一体化方式（虽然我觉得没什么必要



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alex ***@***.***&gt;
发送时间: 2022年4月4日 18:29
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 请问，midway-react-ssr 是否支持midway函数式一体化的方式开发 (Issue #178)





 
请问，midway-react-ssr 是否支持midway函数式一体化的方式开发，有小伙伴试过吗，我看到 官方提供的demo是midway 的标准模式

**Comment by sinianzhiren** [comment]
了解了，谢谢
