### ISSUE TITLE
初始化项目后语法检查报错

### ISSUE THREAD

**Issue by tianull** [ykfe/ssr#181]
初始化项目后，在web下组件引入都会有如下报错
```
Brief' is declared but its value is never read.Vetur(6133)
Cannot find module '@/components/brief/index.vue' or its corresponding type declarations.Vetur(2307)
```
不影响编译，就是开发过程中会一直有错误提示，请问这个该如何处理？
ps. 在config.ts中设置alias发现指向的是编译后的地址，开发过程中的 '@'指向的是src目录，不是web

**Comment by zhangyuang** [comment]
webpack alias跟tsconfig paths是两码事

**Comment by tianull** [comment]
明白了，谢谢大佬

**Comment by zhangyuang** [comment]
搞清楚webpack alias跟tsconfig paths是两个东西



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tianshiwei ***@***.***&gt;
发送时间: 2022年4月6日 11:27
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 初始化项目后语法检查报错 (Issue #181)





 
初始化项目后，在web下组件引入都会有如下报错
 Brief' is declared but its value is never read.Vetur(6133) Cannot find module '@/components/brief/index.vue' or its corresponding type declarations.Vetur(2307)  
不影响编译，就是开发过程中会一直有错误提示，请问这个该如何处理？
 ps. 在config.ts中设置alias发现指向的是编译后的地址，开发过程中的 '@'指向的是src目录，不是web
