### ISSUE TITLE
Vue类型项目里的vuex使用Map对象的话会被替换成`{}`

### ISSUE THREAD

**Issue by fimars** [ykfe/ssr#183]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题

Vue类型项目里的vuex使用Map对象的话会被替换成`{}`

## 期望的结果

保留 Map 字段的类型

## 当前使用的版本

最新版本

## 复现仓库地址

<img width="145" alt="image" src="https://user-images.githubusercontent.com/16299018/162140112-9ce25baa-91f8-4131-9542-a19e1c442dd7.png">

vuex里写一个Map就能复现

## 你本人对问题可能的原因判断(如果你能大概判断的话)

看了一下应该是 `createStore` 里用的 `ssr-deepclone` 的实现的结果，是设计如此吗，后面会怎么处理

**Comment by zhangyuang** [comment]
fix by ssr-deepclone@1.0.1 https://github.com/zhangyuang/ssr-deepclone/blob/master/esm.js#L867

重新安装依赖即可

**Comment by fimars** [comment]
红多尼阿里嘎多
