### ISSUE TITLE
期待的脚手架: midwayjs 3.0 + vue3 + vite + Pinia

### ISSUE THREAD

**Issue by yuwade** [ykfe/ssr#187]
# 期待的脚手架: midwayjs 3.0 + vue3 + vite + Pinia
[点赞]

**Comment by zhangyuang** [comment]
可以尝试用nest

**Comment by zhangyuang** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/17424434/163178942-b2254cbd-b6e2-4732-8736-a3dbfd58b94c.png">
最新脚手架已支持创建pinia的模版
