### ISSUE TITLE
文档优化意见收集

### ISSUE THREAD

**Issue by i5ting** [ykfe/ssr#19]
你期待的好用的文档是怎么样的？
文档是否缺失了什么？
希望哪些部分更加详细？

关于文档的任何意见，欢迎直接反馈到这里，我们会持续优化。

**Comment by juzhiyuan** [comment]
目前 [Apache APISIX](https://apisix.apache.org/) 正在基于 [Docusaurus](https://v2.docusaurus.io/) 改造文档站，我们着重关注：

**功能**
- 多版本（历史版本）；
- 国际化；
- 多语言；

**质量**
- 文档质量：准确性、时效性；

**参考**
- KongHQ: https://github.com/Kong/docs.konghq.com
- k8s: https://kubernetes.io/docs/home/
- Discussion: https://lists.apache.org/thread.html/r2c8e5372fbaa301433691c3e97b245e0ba8970c91c9486ec22cfc050%40%3Cdev.apisix.apache.org%3E

**Comment by roy2an** [comment]
使用route.ts的配置，发现少了layoutFetch项。

**Comment by zhangyuang** [comment]
> 使用route.ts的配置，发现少了layoutFetch项。

layoutFetch 有则执行，没有也不影响使用

**Comment by byoungd** [comment]
是否可以提供一份指导 方便用户从nuxt迁移至ssr框架

**Comment by zhangyuang** [comment]
@byoungd 参考 http://doc.ssr-fc.com/docs/features$faq#%E4%BB%8E%E4%BC%A0%E7%BB%9F%20React%7CVue%20%E9%A1%B9%E7%9B%AE%E8%BF%81%E7%A7%BB

**Comment by xiaoqianghaochi** [comment]
如何加入前端ui库如element

**Comment by ygs-code** [comment]
你好，写的不错，可以帮我做个友谊连接也推广下我的ssr框架么？https://github.com/ygs-code/react-ssr-lazy-loading 支持ssr和csr同构。

**Comment by ygs-code** [comment]
你好，写的不错，可以帮我做个友谊连接也推广下我的ssr框架么？这是我写的ssr框架 https://github.com/ygs-code/react-ssr-lazy-loading 支持ssr和csr路由同构，  支持 ssr+spa渲染

**Comment by i5ting** [comment]
> 

差别是啥？为啥又需要重新写一个呢？

**Comment by Fengjing95** [comment]
ssr-fc.com 域名貌似被劫持了 (´･Д･)」

**Comment by zhangyuang** [comment]
你那边看到的现象是什么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小枫 ***@***.***&gt;
发送时间: 2026年1月20日 18:25
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 文档优化意见收集 (#19)



Fengjing95 left a comment (zhangyuang/ssr#19)
 
ssr-fc.com 域名貌似被劫持了 (´･Д･)」

**Comment by Fengjing95** [comment]
> 你那边看到的现象是什么？
> 
> 
> 
> 发自我的iPhone
> […](#)

<img width="642" height="1389" alt="Image" src="https://github.com/user-attachments/assets/730c890d-cf94-4ec6-b44e-2059fb89c494" />
这样

**Comment by zhangyuang** [comment]
这个是正常页面这个就是部署的example，doc.ssr-fc.com才是文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小枫 ***@***.***&gt;
发送时间: 2026年1月20日 18:46
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 文档优化意见收集 (#19)



Fengjing95 left a comment (zhangyuang/ssr#19)
  
你那边看到的现象是什么？
 
发自我的iPhone
 …
  IMG_7863.png (view on web) 这样
