### ISSUE TITLE
如何实现路由多语言

### ISSUE THREAD

**Issue by zivenday** [ykfe/ssr#193]
比如法语有一个法语后缀https://zfletch.github.io/react-router-i18n/fr/

类似像https://zfletch.github.io/react-router-i18n/pig/

一种是复制一套代码放在对应语言的文件夹下。
这样的话就是如果多套语言，就有多套前端代码。

能不能共用一套代码

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$faq#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1%E5%89%8D%E7%BC%80

**Comment by zhangyuang** [comment]
为什么要复制代码啊，直接/:language在前端组件里处理就行了啊

**Comment by zivenday** [comment]
比如说/fr/detail/sdsfsd,/zh/detail/124

**Comment by zivenday** [comment]
> 为什么要复制代码啊，直接/:language在前端组件里处理就行了啊
比如说/fr/detail/123,/zh/detail/124,怎么搞
$langrender$id.ts 不行


有具体的例子吗

**Comment by zhangyuang** [comment]
你自己在业务代码里控制渲染同一个子组件就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zivenday ***@***.***&gt;
发送时间: 2022年4月19日 08:01
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 如何实现路由多语言 (Issue #193)





 
比如说/fr/detail/sdsfsd,/zh/detail/124

**Comment by zhangyuang** [comment]
`/index/render$language$detail$chapters `文件  对应 `/:language/:detail/:chapters` 路由

**Comment by Joycezhangw** [comment]
还要对不同的语言，获取不同的数据。也是通过 ``:language`` 来处理吗？

**Comment by Phecda** [comment]
如果想用类似苹果官网那种动态前缀该怎么办呢？
```
https://www.apple.com/imac-24/
https://www.apple.com/ca/imac-24/
https://www.apple.com/hk/imac-24/
```
===


> `/index/render$language$detail$chapters `文件 对应 `/:language/:detail/:chapters` 路由

这个意思是用 index 的参数来实现动态前缀的效果吗？

**Comment by zhangyuang** [comment]
都可以呀。搞个 `/:language/:detail/:chapters` 对应的页面组件，或者搞一个`/:language？/:detail/:chapters` 这样的可选参数对应的页面组件。反正能让请求path有对应的页面组件就行了。再在这些页面组件里面去引入一些用于实现公用的国际化子组件

**Comment by Phecda** [comment]
还是有点没理解，是说以下目录
```
├── pages
│   ├── detailA
│   │   ├── fetch.ts
│   │   └── render$id.tsx
│   └── index
│       ├── fetch.ts
│       └── render.tsx
```
改成
```
├── pages
│   └── index
│       ├── fetch$lang#$detailA$id.ts
│       ├── render$lang#$detailA$id.ts
│       ├── fetch$lang#.ts
│       └── render$lang#.tsx
```
吗？把所有index之外的路由打平到index下？

**Comment by zhangyuang** [comment]
搜文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Joyce Zhang ***@***.***&gt;
发送时间: 2022年6月15日 11:44
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 如何实现路由多语言 (Issue #193)





 
还要对不同的语言，获取不同的数据。也是通过 :language 来处理吗？
