### ISSUE TITLE
有考虑升级支持 react 18 吗？

### ISSUE THREAD

**Issue by arleyGuoLei** [ykfe/ssr#195]
FYI

**Comment by zhangyuang** [comment]
后续会考虑支持（目前看起来react18意义不大

**Comment by tulies** [comment]
> 

是时候支持啦。

**Comment by desonyuan** [comment]
还是react17吗？跟新一下啊 大佬。

**Comment by zhangyuang** [comment]
目前看来没有升级的必要性 17的功能已经足够99%的场景使用。有兴趣贡献plugin-react18的可以扫码加群我会帮忙reviewe代码

**Comment by zhangyuang** [comment]
react18已经支持

**Comment by zhangyuang** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/17424434/219951075-a2318e9a-ba1f-4345-9449-0772813234d3.png">
已发版
