### ISSUE TITLE
为什么ssr渲染出的页面不使用 <style> 而是 <link> 引入首屏需要的 css?

### ISSUE THREAD

**Issue by Mistrain-y-y** [ykfe/ssr#202]
link 引入会导致页面闪烁的问题， 为什么不将首屏需要的 css 代码用 <style> 插入 <head> 中呢？

**Comment by zhangyuang** [comment]
link跟style没有任何区别，有问题给复现



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mistrain ***@***.***&gt;
发送时间: 2022年5月22日 18:38
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 为什么ssr渲染出的页面不使用 <style&gt; 而是 <link&gt; 引入首屏需要的 css? (Issue #202)





 
link 引入会导致页面闪烁的问题， 为什么不将首屏需要的 css 代码用 <style&gt; 插入  中呢？

**Comment by Mistrain-y-y** [comment]
我尝试在3G网下进行加载，在 css 文件没有加载出来以前，会呈现出没有样式的页面。为什么不像 nuxt 一样将首屏样式直接加在 <style> 标签中呢？
<img width="796" alt="image" src="https://user-images.githubusercontent.com/72647648/169691427-61dba3e7-ffe9-4aa7-a71f-ff058608e3cd.png">

**Comment by zhangyuang** [comment]
本来就没有任何区别啊。放在style无非是把独立文件的内容放在页面文档里同样会增大文档体积。如果你网络慢同样文档下载慢，如果你只有静态资源慢那你应该换一个cdn



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mistrain ***@***.***&gt;
发送时间: 2022年5月22日 18:46
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 为什么ssr渲染出的页面不使用 <style&gt; 而是 <link&gt; 引入首屏需要的 css? (Issue #202)





 
我尝试在3G网下进行加载，在 css 文件没有加载出来以前，会呈现出没有样式的页面。为什么不像 nuxt 一样将首屏样式直接加在 <style&gt; 标签中呢？

**Comment by Mistrain-y-y** [comment]
那我应该如何解决样式闪动的问题呢？

**Comment by zhangyuang** [comment]
那明显用link不会导致闪烁啊这是基本的dom知识。如果有问题那就是你自己代码的问题可以给复现-。-



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mistrain ***@***.***&gt;
发送时间: 2022年5月22日 18:52
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 为什么ssr渲染出的页面不使用 <style&gt; 而是 <link&gt; 引入首屏需要的 css? (Issue #202)





 
那我应该如何解决样式闪动的问题呢？

**Comment by Mistrain-y-y** [comment]
嗯嗯不知道为什么我的 js 打包进了一部分首屏样式，当 js 加载完又重新渲染了一次

**Comment by zhangyuang** [comment]
大概率是你用了css in js这种ui模块例如material ui



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mistrain ***@***.***&gt;
发送时间: 2022年5月22日 19:46
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 为什么ssr渲染出的页面不使用 <style&gt; 而是 <link&gt; 引入首屏需要的 css? (Issue #202)





 
嗯嗯不知道为什么我的 js 打包进了一部分首屏样式，当 js 加载完又重新渲染了一次

**Comment by Mistrain-y-y** [comment]
我使用的是 vue3 和 vant3， 不清楚它们是否涉及到 css in js。另外，我应该怎样避免这个问题呢。

**Comment by zhangyuang** [comment]
给复现….



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mistrain ***@***.***&gt;
发送时间: 2022年5月22日 20:46
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 为什么ssr渲染出的页面不使用 <style&gt; 而是 <link&gt; 引入首屏需要的 css? (Issue #202)





 
我使用的是 vue3 和 vant3， 不清楚它们是否涉及到 css in js。另外，我应该怎样避免这个问题呢。

**Comment by zhangyuang** [comment]
提供复现仓库后open新的issue
