### ISSUE TITLE
node16 环境下，代理异常

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#206]
配置信息：
<img width="405" alt="image" src="https://user-images.githubusercontent.com/21193805/172826748-e1d4a7bc-64ed-477e-8f4f-5ac7d97ca453.png">
请求：
http://127.0.0.1:3000/base/refreshToken
提示：
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/21193805/172827037-37ae62c3-f6ee-41b0-b9f8-4e8fb017703a.png">

https://github.com/chimurai/http-proxy-middleware/issues/727

版本信息：
├─ http-proxy-middleware@1.3.1
├─ ssr-client-utils@6.2.9
├─ ssr-common-utils@6.2.23
├─ ssr-core-react@6.2.12
├─ ssr-hoc-react@6.2.7
├─ ssr-plugin-midway@6.2.12
├─ ssr-plugin-react@6.2.21
├─ ssr-serialize-javascript@6.0.4
├─ ssr-server-utils@6.2.25
├─ ssr-types-react@6.2.8
├─ ssr-types@6.2.13
├─ ssr-webpack@6.2.10
├─ ssr-window@3.0.0
├─ ssr@6.2.18
├─ ssri@7.1.1
├─ webpack-dev-server-ssr@3.10.8
│  └─ http-proxy-middleware@0.19.1
node版本： v16.13.0

**Comment by zhangyuang** [comment]
这个看起来是非ssr框架自身的问题，可以关注`http-proxy-middleware`的回复
