### ISSUE TITLE
火狐浏览器f5一直刷新会错误跳转，报错

### ISSUE THREAD

**Issue by zpfZPFgithub** [ykfe/ssr#208]
### 环境：火狐浏览器
![图片](https://user-images.githubusercontent.com/4669628/173311498-8010351e-461c-4ca1-a92f-4513a6b0e3e0.png)
### 场景
vue2-midway，直接下载例子
### 问题

- npm run prod后进入首页，随便进入一个二级页面，按住f5刷新，日志里有报错并且页面url跳转到首页了(报错后跳转了)

- 去除koa-static-cache缩小调试范围，url不会跳转到首页，但是日志依然会有报错
![图片](https://user-images.githubusercontent.com/4669628/173312339-e334653c-da6a-4cc2-bec0-d7580baf6798.png)

## 期望的结果

- 不跳转首页
- 日志没有报错

## 当前使用的版本
vue2-midway，直接下载最新的例子

## 你本人对问题可能的原因判断(如果你能大概判断的话)
- koa-static-cache问题？
- 写入流问题？

**Comment by zhangyuang** [comment]
可能是请求量太大处理不过来，建议生产环境可以添加拦截器，拦截大量重复ip的请求，静态资源托管服务建议用独立cdn服务或者koa-static，koa-static-cache中存在同步逻辑会拉低性能
