### ISSUE TITLE
vite 模式下 react 引入antd 报错，根据示例项目创建

### ISSUE THREAD

**Issue by muyichuanqi** [ykfe/ssr#209]
vite 模式下 react 引入antd 报错，根据示例项目创建

**Comment by muyichuanqi** [comment]
![image](https://user-images.githubusercontent.com/12714782/174204375-e59b99e8-86b2-4f02-a5a6-03f7c1ac545b.png)

**Comment by zhangyuang** [comment]
提供复现代码,button没有问题

**Comment by muyichuanqi** [comment]
引入menu 试试

**Comment by zhangyuang** [comment]
直接给复现代码

**Comment by muyichuanqi** [comment]
发群里了
