### ISSUE TITLE
可以支持unplugin-vue-components的按需加载吗

### ISSUE THREAD

**Issue by suktec** [ykfe/ssr#215]
不用手动引入组件还是挺方便的

**Comment by zhangyuang** [comment]
不需要引入`unplugin-vue-components` 默认就是按需加载，仔细看文档

**Comment by suktec** [comment]
不好意思，我的表述不是很清楚。我的意思是目前框架使用的是babel-plugin-import按需加载，使用的时候需要手动import组件。
如果改为unplugin-vue-components按需加载，可以不需要手写import语句。

**Comment by zhangyuang** [comment]
1、vite场景没有用 `babel-plugin-import`, 已经自动集成了 `vite-plugin-style-import`
2、`unplugin-vue-components` 在 `ui组件`的场景下做的事情看起来直接跟在 app.vue 里面 use 全局使用一样，没看出有集成的必要
3、有需要自行参考  `vite-plugin-style-import`的 resolver 引入 `unplugin-vue-components`

**Comment by suktec** [comment]
好的，我继续摸索一下。谢谢回复。
