### ISSUE TITLE
Access to process.binding("http_parser") is deprecated

### ISSUE THREAD

**Issue by bdatacloud-liushanshan** [ykfe/ssr#217]
## 问题
![1657015336196](https://user-images.githubusercontent.com/92718549/177303714-48d617b3-6b94-4f28-8960-4689b02db8ac.jpg)

## 期望
废弃了为啥还会调用，0改动，拉下来跑就出来了这个错误

**Comment by zhangyuang** [comment]
底层库调用 忽略



发自我的iPhone


------------------ Original ------------------
From: 刘山山 ***@***.***&gt;
Date: Tue,Jul 5,2022 6:09 PM
To: zhangyuang/ssr ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/ssr] Access to process.binding("http_parser") isdeprecated (Issue #217)





 
问题
 

 
期望
 
废弃了为啥还会调用，0改动，拉下来跑就出来了这个错误
