### ISSUE TITLE
前端路由是不是必须得配合后端路由使用？

### ISSUE THREAD

**Issue by bdatacloud-liushanshan** [ykfe/ssr#218]
## 详细描述你的问题
我只在文档中找到了下面图片的路由说明，路由必须得双端统一吗？那多人协作的方式是不是不太友好，意思其他人写了个页面，我必须得添加一个对应controller页面才能看到吗？。
![image](https://user-images.githubusercontent.com/92718549/177454466-0a2bc8ff-d297-40df-8202-28e71249950d.png)

**Comment by zhangyuang** [comment]
与框架无关，可以用中间件or通配符减少重复代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘山山 ***@***.***&gt;
发送时间: 2022年7月6日 10:28
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 前端路由是不是必须得配合后端路由使用？ (Issue #218)





 
详细描述你的问题
 
我只在文档中找到了下面图片的路由说明，路由必须得双端统一吗？那多人协作的方式是不是不太友好，意思其他人写了个页面，我必须得添加一个对应controller页面才能看到吗？。

**Comment by bdatacloud-liushanshan** [comment]
理解你的意思
