### ISSUE TITLE
该框架支持主应该SSR，子应该不是SSR么？

### ISSUE THREAD

**Issue by palluo** [ykfe/ssr#220]

**Comment by zhangyuang** [comment]
文档搜微前端



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 图信空间 ***@***.***&gt;
发送时间: 2022年7月9日 14:23
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 该框架支持主应该SSR，子应该不是SSR么？ (Issue #220)
