### ISSUE TITLE
支持 config.ts 引入外部 ts 文件

### ISSUE THREAD

**Issue by jiangmaniu** [ykfe/ssr#225]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题

目前业务上有个需求，就是根据一个常量配置文件，来控制 `customeHeadScript` 是否载入后某些模块，我给这个属性的值执行一个方法，这个方法会动态的返回要插入到 head 的 script 脚本数组，但我在引入常量配置文件的变量时，发现会报以下错误：

![image](https://user-images.githubusercontent.com/50100681/179435873-e59c9037-7ab2-4e69-b5b0-cba1fc5a5227.png)

我在翻看官网文档时，发现已经注明：

> 目前不支持引入外部 ts 文件

请问近期是否有支持引入外部 ts 的计划？或者这个业务场景该如何实现？

## 期望的结果

支持引入外部 ts 文件

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
暂时没什么支持的打算。config 开发/生产环境都会在node环境原生调用，node环境不支持ts文件。目前框架先用esbuild处理了一遍。涉及到外部ts文件的话要做批量处理还要处理文件路径的关系，config.ts将会被编译为build/config.js。有需要可自行用babel/tsc/esbuild预编译外部ts文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 江麻妞 ***@***.***&gt;
发送时间: 2022年7月18日 10:13
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 支持 config.ts 引入外部 ts 文件 (Issue #225)





 
提问前请确认以下几点信息，否则你的问题将不会被解答
  
参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式 

确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案 

对应服务端框架的使用问题请去它们的官方文档找答案。例如 Midway, Nest.js 

如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭 

原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。 
 
详细描述你的问题
 
目前业务上有个需求，就是根据一个常量配置文件，来控制 customeHeadScript 是否载入后某些模块，我给这个属性的值执行一个方法，这个方法会动态的返回要插入到 head 的 script 脚本数组，但我在引入常量配置文件的变量时，发现会报以下错误：
 

 
我在翻看官网文档时，发现已经注明：
  
目前不支持引入外部 ts 文件
  
请问近期是否有支持引入外部 ts 的计划？或者这个业务场景该如何实现？
 
期望的结果
 
支持引入外部 ts 文件
 
当前使用的版本
 
不要贴 package.json 用 yarn list "ssr*"  来查看版本。同时建议熟读semver 规则并且知道怎么安装最新依赖！
 
复现仓库地址
 
超过一行代码能描述的问题必须提供复现地址, 用默认的 example 给最简单的复现代码不要给包含着一堆业务代码的仓库
 
你本人对问题可能的原因判断(如果你能大概判断的话)

**Comment by zhangyuang** [comment]
你这个报错是路径问题。and你这个写法也不对应用配置文件不要放在web下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 江麻妞 ***@***.***&gt;
发送时间: 2022年7月18日 10:13
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 支持 config.ts 引入外部 ts 文件 (Issue #225)





 
提问前请确认以下几点信息，否则你的问题将不会被解答
  
参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式 

确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案 

对应服务端框架的使用问题请去它们的官方文档找答案。例如 Midway, Nest.js 

如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭 

原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。 
 
详细描述你的问题
 
目前业务上有个需求，就是根据一个常量配置文件，来控制 customeHeadScript 是否载入后某些模块，我给这个属性的值执行一个方法，这个方法会动态的返回要插入到 head 的 script 脚本数组，但我在引入常量配置文件的变量时，发现会报以下错误：
 

 
我在翻看官网文档时，发现已经注明：
  
目前不支持引入外部 ts 文件
  
请问近期是否有支持引入外部 ts 的计划？或者这个业务场景该如何实现？
 
期望的结果
 
支持引入外部 ts 文件
 
当前使用的版本
 
不要贴 package.json 用 yarn list "ssr*"  来查看版本。同时建议熟读semver 规则并且知道怎么安装最新依赖！
 
复现仓库地址
 
超过一行代码能描述的问题必须提供复现地址, 用默认的 example 给最简单的复现代码不要给包含着一堆业务代码的仓库
 
你本人对问题可能的原因判断(如果你能大概判断的话)

**Comment by jiangmaniu** [comment]
好的，我明白了，谢谢你！
