### ISSUE TITLE
React扩展Reducer问题

### ISSUE THREAD

**Issue by aldabil21** [ykfe/ssr#227]
## 详细描述你的问题
根据文档[扩展自定义 Reducer](http://doc.ssr-fc.com/docs/features$communication#%E6%89%A9%E5%B1%95%E8%87%AA%E5%AE%9A%E4%B9%89%20Reducer), 以及[import store statement](https://github.com/zhangyuang/ssr/blob/f48f8edfcbf902c4035694bcadac421046d13c52/packages/plugin-react/src/entry/context.tsx#L10)这里，框架应该混合自己的default reducer, 和用户自己写的的state/reducer.

只不过在这个情况下，用户不能利用自己创建的store, 因为[state, reducer](https://github.com/zhangyuang/ssr/blob/f48f8edfcbf902c4035694bcadac421046d13c52/packages/plugin-react/src/entry/context.tsx#L10)这里总是undefined。实际上是`store?.state`与`store?.reducer`

## 期望的结果
import statement应该包括用户创建的state, reducer 

## 当前使用的版本
6.2.x

## 复现仓库地址
参考[仓库](https://github.com/aldabil21/ssr/tree/fix/react-store).
我已修改 `ReactRoutesType` 和 import statements. 如果觉得这个解决方案是可以的，我以下连 PR。

## 你本人对问题可能的原因判断(如果你能大概判断的话)
或许`ssr-declare-route`由 `export * as store from "@/store/index"`的statement (?)

**Comment by zhangyuang** [comment]
没懂你的具体问题是什么，按照文档示例跑不通？

**Comment by zhangyuang** [comment]
你这就是把 state,reducer合并到了store，跟单独export state, reducer 有什么区别？

**Comment by aldabil21** [comment]
[这里](https://github.com/zhangyuang/ssr/blob/f48f8edfcbf902c4035694bcadac421046d13c52/packages/plugin-react/src/entry/context.tsx#L10) state/reducer总是undefined.
自己创建的store怎么弄也都不会和框架的state/reducer混合的。

**Comment by zhangyuang** [comment]
总是 undefined 是因为你没导出呀，这里读的就是开发者的 state,reducer

**Comment by aldabil21** [comment]
已经导出的就像文档解释的[这里](http://doc.ssr-fc.com/docs/features$communication#%E6%89%A9%E5%B1%95%E8%87%AA%E5%AE%9A%E4%B9%89%20Reducer)
请 `console` state, reducer
`const { reducer, state } = Routes `
再`console` store value
`const { store } = Routes `

**Comment by zhangyuang** [comment]
哦我知道问题了，这里是上次修 vue 的bug的时候把react这种情况忽略了
