### ISSUE TITLE
最新版本启动报错

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#229]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/21193805/179877944-1fd2e25d-4db6-44d3-870b-7740c0c4700e.png">

版本：
├─ ssr-client-utils@6.2.9
├─ ssr-common-utils@6.2.23
├─ ssr-core-react@6.2.12
│  └─ ssr-server-utils@6.2.38
├─ ssr-hoc-react@6.2.7
├─ ssr-plugin-midway@6.2.15
│  └─ ssr-server-utils@6.2.38
├─ ssr-plugin-react@6.2.36
│  └─ ssr-server-utils@6.2.38
├─ ssr-serialize-javascript@6.0.4
├─ ssr-server-utils@6.2.53
├─ ssr-types-react@6.2.8
├─ ssr-types@6.2.18
├─ ssr-vite-plugin-style-import@2.0.1
├─ ssr-webpack@6.2.10
│  └─ ssr-server-utils@6.2.38
├─ ssr-window@3.0.0
├─ ssr@6.2.28
│  └─ ssr-server-utils@6.2.38
├─ ssri@7.1.1
└─ webpack@4.46.0
   └─ ssri@6.0.2

**Comment by zhangyuang** [comment]
明显不是最新版本
