### ISSUE TITLE
ssr的使用文档在哪里，没看到啊，能弄在醒目的位置吗

### ISSUE THREAD

**Issue by Ben-Ben-B** [ykfe/ssr#23]

**Comment by zhangyuang** [comment]
readme已经写的足够详细啦你能够用到的功能在readme都能找到答案。或者也可以先看之前的 https://github.com/ykfe/egg-react-ssr 文档来进行深入了解。
独立的官网会在结合完 vite 后发布。

**Comment by Ben-Ben-B** [comment]
@zhangyuang 还是没看懂，这个如何配置SEO的，<slot name="customeHeadScript" />这个自定义的 script如何使用等等，没看到那个地方有写，我比较菜

**Comment by zhangyuang** [comment]
https://github.com/ykfe/ssr#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2%E6%A0%87%E9%A2%98-meta-%E7%AD%89%E4%BF%A1%E6%81%AF
这里已经写了，还有不懂的扫码加群

**Comment by Ben-Ben-B** [comment]
@zhangyuang 好的，谢谢

**Comment by Ben-Ben-B** [comment]
![image](https://user-images.githubusercontent.com/30291896/110089250-d54a0680-7dd0-11eb-9a9f-966358dc2afd.png)
@zhangyuang 这个钉钉二维码显示不了，能在发一个吗

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/110089451-1b9f6580-7dd1-11eb-8546-5fa8f043ff50.png)
显示不了是网络问题可以挂代理
