### ISSUE TITLE
怎么使用路由守卫

### ISSUE THREAD

**Issue by pmh1314** [ykfe/ssr#231]
以往纯vue项目，可以在router.beforeEach路由守卫判断是否有token等，在这个ssr框架应该怎么实现此功能？？

**Comment by zhangyuang** [comment]
能拿到router就行了，vue2就是this.$router，vue3就是useRouter

**Comment by zhangyuang** [comment]
搜文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pmh1314 ***@***.***&gt;
发送时间: 2022年8月2日 12:29
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么使用路由守卫 (Issue #231)





 
以往纯vue项目，可以在router.beforeEach路由守卫判断是否有token等，在这个ssr框架应该怎么实现此功能？？
