### ISSUE TITLE
怎么增加环境变量的配置

### ISSUE THREAD

**Issue by pmh1314** [ykfe/ssr#232]
实际开发过程中会有开发环境、测试环境、生产环境。按道理NODE_ENV应有三个值，当目前来看只有'development'和'production'，怎么给NODE_ENV增加测试环境的‘test’值呢

**Comment by zhangyuang** [comment]
不要用nodeenv自己定义一个新的env就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pmh1314 ***@***.***&gt;
发送时间: 2022年8月3日 17:50
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么增加环境变量的配置 (Issue #232)





 
实际开发过程中会有开发环境、测试环境、生产环境。按道理NODE_ENV应有三个值，当目前来看只有'development'和'production'，怎么给NODE_ENV增加测试环境的‘test’值呢

**Comment by pmh1314** [comment]
是指使用cross-env在package.json的scripts里面添加么？

**Comment by zhangyuang** [comment]
你应该是要在前端代码里面拿，用 `config.define`

**Comment by zhangyuang** [comment]
https://github.com/zhangyuang/ssr/commit/777c80b7189dfed309d961928bf8ca910066f684#diff-23e5629f576cd9341630f6b5e26c7b76b6b9ba753648bc0777867f32ceaa8125R215
最新版本支持直接将Node环境变量注入到前端代码中，可直接在 scipt 中定义 env

**Comment by pmh1314** [comment]
重新下载ssr依赖？文档中有没有给出示例说明了呢？
