### ISSUE TITLE
ui框架使用ant-design-vue，按需引入input-search组件时报错

### ISSUE THREAD

**Issue by pmh1314** [ykfe/ssr#233]
## 详细描述你的问题
![1659614307(1)](https://user-images.githubusercontent.com/85694056/182841747-29f55481-9247-41f3-804e-b20350308140.png)
使用midway-vue3-ssr模板，ui框架使用ant-design-vue，按需引入input-search组件时，终端报错：Error: Cannot find module 'ant-design-vue/lib/input-search/style'。页面展示：Internal Server Error, real status: 500

## 期望的结果
按需引入input-search组件时，能够引入正确的样式文件，组件可以正常使用，终端不报错，页面正常展示

## 当前使用的版本
ssr@6.2.31

## 你本人对问题可能的原因判断(如果你能大概判断的话)
可能在做按需引入配置时需要添加部分特殊组件样式映射表

**Comment by zhangyuang** [comment]
```js
import { Input } from 'ant-design-vue'
const search = Input.Search
```

**Comment by pmh1314** [comment]
感谢！！
