### ISSUE TITLE
使用ant-design-vue，切换语言报错Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pmh1314** [ykfe/ssr#236]
## 详细描述你的问题
ant-design-vue 目前的默认文案是英文，例：
![1660795507(1)](https://user-images.githubusercontent.com/85694056/185291243-00bfb75c-d0d3-4727-bb54-8a83604cdbae.png)

想要改成中文，代码如下：
![1660795403(1)](https://user-images.githubusercontent.com/85694056/185291030-affbd007-8a67-4c3f-bcb2-301782236de6.png)
![1660795439(1)](https://user-images.githubusercontent.com/85694056/185291110-12754562-6673-435d-b45e-771a3f1ba9e5.png)

报错：Cannot use import statement outside a module
![1660795789(1)](https://user-images.githubusercontent.com/85694056/185291790-43212017-2c51-4b22-8453-543003f7c45f.png)

## 期望的结果
![1660795533(1)](https://user-images.githubusercontent.com/85694056/185291292-9471bbc3-adb8-4b99-904b-8e1c10238718.png)

## 当前使用的版本
ssr@6.2.31

## 你本人对问题可能的原因判断(如果你能大概判断的话)
node环境不支持ES6语法
但是配置config.ts无效果：
babelExtraModule: [/ant-design-vue/]

**Comment by zhangyuang** [comment]
看文档whitelist



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pmh1314 ***@***.***&gt;
发送时间: 2022年8月18日 12:10
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 使用ant-design-vue，切换语言报错Cannot use import statement outside a module (Issue #236)





 
详细描述你的问题
 
ant-design-vue 目前的默认文案是英文，例：
 
 
想要改成中文，代码如下：
 
 
 
报错：Cannot use import statement outside a module
 
 
期望的结果
 

 
当前使用的版本
 
***@***.***
 
复现仓库地址
 
你本人对问题可能的原因判断(如果你能大概判断的话)
 
node环境不支持ES6语法
 但是配置config.ts无效果：
 babelExtraModule: [/ant-design-vue/]

**Comment by pmh1314** [comment]
可以了，感谢！
