### ISSUE TITLE
Hydration completed but contains mismatches.

### ISSUE THREAD

**Issue by vrockn** [ykfe/ssr#237]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
Hydration text mismatch:
- Client: " main 登录 你好 世界"
- Server: " main Login Hello World" 
  at <ElMain height=undefined > 
  at <ElContainer> 
  at <ElContainer> 
  at <Index is-header="true" is-footer="true" > 
  at <Render reactiveFetchData= Object fetchData= Object onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <RouterView reactiveFetchData= Object fetchData= Object > 
  at <App asyncData= Object fetchData= Object reactiveFetchData= Object  ... > 
  at <App>

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
给复现，这明显是业务代码自己的问题

**Comment by vrockn** [comment]
https://github.com/Rockny/EasyWeb

**Comment by vrockn** [comment]
我不知道要怎么处理这个错误，本地存储后客户端修改语言就会出现这种情况。

**Comment by vrockn** [comment]
![image](https://user-images.githubusercontent.com/15974713/185866309-4b1ad370-f098-4c0b-bb75-4008d5a09db7.png)
只要一切换就会出现这种情况

**Comment by zhangyuang** [comment]
明显是业务代码自己的问题没有对齐服务端/客户端的初始状态，不知道怎么做就用/zh | /en 来判断状态。
