### ISSUE TITLE
antd-vue框架Cascader级联组件不能正常使用

### ISSUE THREAD

**Issue by pmh1314** [ykfe/ssr#238]
提问前请确认以下几点信息，否则你的问题将不会被解答

## 详细描述你的问题
使用antd-vue框架里面的Cascader级联组件时，选项列表只有第一个选项旁出现展开箭头，其余选项旁没有展开箭头（正常是所有选项旁都有展开箭头的），且相关展开功能会有问题。
![1661482471(1)](https://user-images.githubusercontent.com/85694056/186806540-2905117f-91d2-4a2e-aa70-935e0b12c097.jpg)

我检查自己业务代码，并没有对相关样式做隐藏。查看控制台元素，发现第一个选项下是有生成anticon-right图标的，其余选项没有。
![1661482675(1)](https://user-images.githubusercontent.com/85694056/186808208-0494c4ba-be75-415b-a08e-95f05bcfca67.png)

我尝试slot自定义展开图标，发现只要是使用标签图标的，均会出现上述现象
  <template #expandIcon>
    <span><UpOutlined></UpOutlined></span>
  </template>
如果是键盘符号，则正常显示
    <template #expandIcon>
      <span>></span>
    </template>

然后我自己创建了一个新的vue3干净项目（vue@3.2.3，ant-design-vue@3.2.10），使用antd-vue框架里面的Cascader级联组件，是能正常显示展开符号和使用的。

## 期望的结果
Cascader级联组件展开符号正常显示且功能正常
![image](https://user-images.githubusercontent.com/85694056/186808791-a50d7733-e0bf-492b-b412-e3663ba7cafa.png)

## 当前使用的版本

使用midway-vue3-ssr模板
ssr@6.2.31
vue@3.2.3
ant-design-vue@3.2.10

**Comment by zhangyuang** [comment]
这是该组件在 vue ssr下自身的 bug，建议提给 `ant-design-vue` 去修复这个问题。或者用 [onlyCsr](http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E8%AE%A9%E6%9F%90%E4%B8%AA%E7%BB%84%E4%BB%B6%E5%8F%AA%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%B8%B2%E6%9F%93) 让该组件在客户端阶段渲染

**Comment by pmh1314** [comment]
试了一下用onlyCsr也不行，我向ant-design-vue提下bug
