### ISSUE TITLE
pinia在ios中后退页面显示空白

### ISSUE THREAD

**Issue by Ryan2018-js** [ykfe/ssr#241]
nestjs-vue3-ssr-pinia项目，pinia在ios系统中不论是 storeToRefs还是 computed方式得到的响应式数据，一开始页面都显示正常。在列表页进入详情页，然后后退页面就显示空白

**Comment by zhangyuang** [comment]
复现

**Comment by Ryan2018-js** [comment]
问题已定位。列表页用a标签跳转到详情页，然后后退到列表，iOS 就会出现空白页。试了下，点击事件router跳转，后退没问题，computed和storeToRefs已正常使用

**Comment by Ryan2018-js** [comment]
用a标签的同时，也直接调用Node service，以stream形式处理数据。也没有判断当前环境。定位问题后，切换成点击事件，router跳转，采用判断环境的形式，发现跳转详情调用，window.fetch，返回也是。这种情况就没问题
