### ISSUE TITLE
tainwind css用vite时失效

### ISSUE THREAD

**Issue by Ryan2018-js** [ykfe/ssr#242]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
1. nestjs-vue3-ssr-pinia用yarn start:vite，tailwind css样式失效，yarn start时正常。
2. 用yarn start:vite时vscode终端出现reflect-metadata doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

## 期望的结果
期望用vite时tailwind css启作用。reflect-metadata报错问题，不知是否影响使用

## 当前使用的版本
nestjs-vue3-ssr-pinia

## 复现仓库地址

https://github.com/Ryan2018-js/test-ssr.git

**Comment by zhangyuang** [comment]
不影响



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan2018-js ***@***.***&gt;
发送时间: 2022年10月15日 17:28
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] tainwind css用vite时失效 (Issue #242)





 
提问前请确认以下几点信息，否则你的问题将不会被解答
  
参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式 

确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案 

对应服务端框架的使用问题请去它们的官方文档找答案。例如 Midway, Nest.js 

如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭 

原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。 
 
详细描述你的问题
  
nestjs-vue3-ssr-pinia用yarn start:vite，tailwind css样式失效，yarn start时正常。 

用yarn start:vite时vscode终端出现reflect-metadata doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix. 
 
期望的结果
 
期望用vite时tailwind css启作用。reflect-metadata报错问题，不知是否影响使用
 
当前使用的版本
 
nestjs-vue3-ssr-pinia
 
复现仓库地址
 
https://github.com/Ryan2018-js/test-ssr.git
