### ISSUE TITLE
在试用naive-ui，引入n-menu组件，报错：Unhandled error during execution of setup function

### ISSUE THREAD

**Issue by nowodecuo** [ykfe/ssr#243]
使用n-button正常显示组件
![image](https://user-images.githubusercontent.com/49633003/196629602-2a283c2c-23cf-4a93-af69-e51df9be3ac6.png)

使用n-menu时会报错，请问怎么解决呢？
![image](https://user-images.githubusercontent.com/49633003/196630005-26218911-2b10-4858-8dba-09e7ad43b23f.png)

**Comment by zhangyuang** [comment]
看文档

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%8F%AF%E8%AE%BF%E9%97%AE%E7%9A%84%E5%AF%B9%E8%B1%A1%E7%9A%84%E9%97%AE%E9%A2%98
