### ISSUE TITLE
svg-sprite-loader 无法加载svg

### ISSUE THREAD

**Issue by palluo** [ykfe/ssr#244]
提问前请确认以下几点信息，否则你的问题将不会被解答

## 详细描述你的问题
安装下列配置，没有svg加载，dome树中也没有找到svg的节点
chainBaseConfig: (chain, isServer) => {
    setStyle(chain, /\.s[ac]ss$/i, {
      rule: 'sass',
      loader: 'sass-loader',
      isServer,
      importLoaders: 2
    });
    chain.module
      .rule('svg-sprite-loader')
      .test(/\.svg$/)
      .include.add(resolve('./web/assets/svgs')) // 处理svg目录
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      });
  },

![image](https://user-images.githubusercontent.com/24562747/197692236-ce14d5cd-edab-4191-aad9-f677165ebcc5.png)

## 期望的结果
希望可以正常加载svg
## 当前使用的版本
   "ssr": "^6.0.0",
    ssr-plugin-nestjs": "^6.0.0",
   "ssr-plugin-vue3": "^6.0.0",
    "ssr-types": "^6.0.0",
    "svg-sprite-loader": "^6.0.11",

## 你本人对问题可能的原因判断(如果你能大概判断的话)
 猜测没有正常加载到svg目录

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%20svg-sprite-loader

**Comment by palluo** [comment]
是按照上面加载的

**Comment by zhangyuang** [comment]
你没有添加exclude啊

**Comment by palluo** [comment]
![image](https://user-images.githubusercontent.com/24562747/197698210-82e166f9-8f2e-4782-998b-cfdc9c9d461c.png)
都测试过，现在按照文档基本一样配置也不行，帮忙看看

**Comment by zhangyuang** [comment]
查这个loader自己的文档或者不用，一直都不推荐用这个loader

**Comment by palluo** [comment]
那不用这个loader，我看文档中没有写其他加载svg的方案

**Comment by zhangyuang** [comment]
svg直接加载不就行了。。为什么一定要处理
