### ISSUE TITLE
关于在ssr中使用vue-apollo的疑惑

### ISSUE THREAD

**Issue by ElvisUpUp** [ykfe/ssr#248]
我想在我的ssr项目里使用vue-apollo来作为请求graphql的工具，但是vue-apollo的挂载需要在client的初始化阶段，但是ssr框架貌似没有这个阶段或者是没有暴露出来。因此，我想请问一下这里应该如何去解决呢？

**Comment by zhangyuang** [comment]
不需要在client的初始化做，client的初始化阶段能做的事情在app.vue都能做

**Comment by ElvisUpUp** [comment]
好的，感谢回复。是我没有完全看仔细文档了😂
