### ISSUE TITLE
如果是单纯的想做SSR推荐用这个框架吗

### ISSUE THREAD

**Issue by ClearSeve** [ykfe/ssr#252]
后端API已经开发完成了, 想做服务端渲染, 用的前端框架是ant design，看到官方介绍说是支持这个前端框架， 我对别的SSR框架也不太了解有哪些，如题单纯的做前端渲染是否推荐使用该框架， 如果还有其他框架推荐， 有什么框架呢。

**Comment by zhangyuang** [comment]
没有问题，基本都是这么做的
