### ISSUE TITLE
ssr css相关问题咨询

### ISSUE THREAD

**Issue by czz362100** [ykfe/ssr#254]
您好，
请问一下，在vite模式下开发，您这边是如何去解决服务端渲染直出Html并携带相关link css的标签（解决样式闪屏问题）？看了您的源码发现您好像对这一块并没有进行处理，但是直出后的html依然可以渲染样式呢？
<img width="781" alt="image" src="https://user-images.githubusercontent.com/37129738/205792600-9c7c4a5f-e712-4583-9924-59364b273b89.png">

**Comment by czz362100** [comment]
![image](https://user-images.githubusercontent.com/37129738/205846550-73e16a62-b7d8-451d-8aaf-7721cd6c325d.png)
在网速稍慢的情况下，会出现样式闪屏问题。

**Comment by czz362100** [comment]
在网速稍慢的情况下，会出现样式闪屏的问题
![image](https://user-images.githubusercontent.com/37129738/205846767-e6f682b9-8be7-427d-83b9-038ebc3a49fc.png)
![image](https://user-images.githubusercontent.com/37129738/205846812-889d21d3-1ba4-4046-ba53-8cbe42654e1d.png)

**Comment by zhangyuang** [comment]
vite本地开发模式本来就不会携带link标签，建议先去了解下vite的原理。生产环境才会有
