### ISSUE TITLE
使用emotion/react会出现闪屏问题, 有什么代替的解决方案吗

### ISSUE THREAD

**Issue by ClearSeve** [ykfe/ssr#255]
使用emotion/react会出现闪屏问题, 有什么代替的解决方案吗

**Comment by zhangyuang** [comment]
没用过 emotion/react 可以给复现，看起来是类似于 css in js的方案，不推荐用此类型方案的库

**Comment by ClearSeve** [comment]
谢谢您的解答, 这类库应该是对SSR不太友好, 我会尝试别的方法, 移除类似库的使用
