### ISSUE TITLE
打包后vender 体积过大

### ISSUE THREAD

**Issue by qc5926** [ykfe/ssr#257]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
线上部署，vender包体积太大，加载时间太长
![image](https://user-images.githubusercontent.com/66767805/212251268-f9335dfd-f69a-4281-852f-56e608d4390b.png)

## 期望的结果
可以拆分vender包

## 当前使用的版本
v6.0.0

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
`react|vue3` 场景尝试使用 `ssr build --optimize` http://doc.ssr-fc.com/docs/features$faq#%E9%AB%98%E6%80%A7%E8%83%BD%E4%BA%A7%E7%89%A9%E6%9E%84%E5%BB%BA
或使用 `ssr build --vite` 进行构建
`vue2` 场景需要自行拆分 `vendor`, 参考 http://doc.ssr-fc.com/docs/api$config#extraJsOrder%F0%9F%A4%94

**Comment by qc5926** [comment]
"prod": "cross-env FIRST_ENV=production PORT=3000 ssr build --optimize && pm2 start pm2.config.js --only prod"
这样启动之后报错，项目无法进入

![image](https://user-images.githubusercontent.com/66767805/212253150-f985fabb-b4cf-4cc8-b206-8a291bd0651b.png)

**Comment by zhangyuang** [comment]
提供最简复现仓库
