### ISSUE TITLE
nodeJS18.12.1报错

### ISSUE THREAD

**Issue by adoin** [ykfe/ssr#262]
ital envelope routines::unsupported

**Comment by adoin** [comment]
用的vite pinia next那个模板，还是报错的啊。。。

**Comment by zhangyuang** [comment]
`crypto.createHash('md4') is not supported when node version > 16,
    Please use NODE_OPTIONS=--openssl-legacy-provider ssr start to start project
    If you are using windows please use set NODE_OPTIONS=--openssl-legacy-provider, ref https://github.com/webpack/webpack/issues/14532
    `
