### ISSUE TITLE
打包后访问报错

### ISSUE THREAD

**Issue by desonyuan** [ykfe/ssr#265]
初始化一个项目 react-18 midway 里面eslint 报错，这个好修复，启动也磕磕绊绊，打包后运行 报错。。感觉用不到生存环境。问题不少，离地表最强还有距离。。。

## 详细描述你的问题
![image](https://user-images.githubusercontent.com/37859515/220015779-5a1b807f-7c38-434a-ba4d-aba24b7e2a3a.png)

## 期望的结果

内部使用的插件是否太过老旧？考虑升级一下。

**Comment by zhangyuang** [comment]
并没有问题，检查安装的依赖版本是否最新 yarn list "ssr*"

**Comment by desonyuan** [comment]
跑的最新的[midway-react18-ssr](https://github.com/zhangyuang/ssr/tree/dev/example/midway-react18-ssr)开发模式可以访问页面，build 后访问报错

**Comment by zhangyuang** [comment]
build后也没有问题，提供完整复线步骤和复线仓库
