### ISSUE TITLE
如何抽取critical css 并插入到html head中

### ISSUE THREAD

**Issue by jiangjiu** [ykfe/ssr#267]
## 详细描述你的问题
文档中以及issue没有看到如何抽取critical css并内联到html中，以及如何分割critical和非critical css。

## 希望支持的原因
多一个外链css请求，fcp时间要等到  【cdn建连+css请求回来】，失去了ssr快速展现的意义呀

## 期望的结果
支持抽取critical css并内联到html中

**Comment by zhangyuang** [comment]
不认为这个需求是有必要的，一定要自行实现可以使用customehead设置tag为style读取asset-manifest自行插入内容
