### ISSUE TITLE
clientPrefix属性能否支持传对象？

### ISSUE THREAD

**Issue by WadeZhu** [ykfe/ssr#268]
## 详细描述你的问题
项目里的每个page都会作为子应用被不同的基座应用以微前端的方式引用，clientPrefix只能传字符串的话不够用，因为每个基座应用的页面路由不一样。

## 期望的结果

clientPrefix可以传对象，对象的key值为正则字符串，实现根据当前页面url匹配不同的prefix

clientPrefix: {
  '/aurl/mypage': '/aurl',
  '/burl/mypage': '/burl',
  '/curl/id/(.*?)/detail': '/curl'
}

**Comment by zhangyuang** [comment]
`clientPrefix`本来就支持在render方法的配置里动态传入，根据不同的页面调用render的时候传入不同的clientPrefix就行了。微前端在我们这大量应用就是用这种方法

**Comment by WadeZhu** [comment]
您好，你的邮件我已经收到。我将会仔细阅读，并尽快给您回复。
