### ISSUE TITLE
请问我使用tippyjs组件，下拉的菜单不会被返回怎么办，好像是因为tippy初始化下拉菜单设置了display：none

### ISSUE THREAD

**Issue by wangbailu0021** [ykfe/ssr#272]
![飞书20230307-110354](https://user-images.githubusercontent.com/108673238/223309677-575e3cae-dbfd-48eb-ba46-32e9f3d28a80.png)
![飞书20230307-110405](https://user-images.githubusercontent.com/108673238/223309717-130490f0-2f65-462d-87e6-8f45af8c894e.png)

**Comment by zhangyuang** [comment]
给最简复现仓库and这看起来跟ssr框架也没有任何关系是业务代码的问题
