### ISSUE TITLE
suggest to upgrade depended `@typescript-eslint/eslint-plugin`

### ISSUE THREAD

**Issue by Gnosnay** [ykfe/ssr#273]
https://github.com/zhangyuang/ssr/blob/a589ec81c13ce3c328c2f41925dd2e108e1b6bf0/example/midway-react-ssr/package.json#L24

for this linter style, it used 4.x version. but it will cause a lot of complains about `defined but not used`, especially for controller class.

better to upgrade the version to 5.x:

- https://github.com/typescript-eslint/typescript-eslint/issues/5525#issuecomment-1226256085
- https://stackoverflow.com/questions/73591752/eslint-error-is-defined-but-never-used-warning-in-nestjs-for-all-decorators

**Comment by zhangyuang** [comment]
已更新
