### ISSUE TITLE
请问有支持react router 6.x 的计划吗

### ISSUE THREAD

**Issue by 381924237** [ykfe/ssr#275]
部分业务组件依赖react router 6.x，目前没办法使用，后续有考虑升级吗

**Comment by zhangyuang** [comment]
没有这个计划 没有什么升级的必要。可以直接说具体是什么功能要用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XXXXzy ***@***.***&gt;
发送时间: 2023年3月31日 17:35
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 请问有支持react router 6.x 的计划吗 (Issue #275)





 
部分业务组件依赖react router 6.x，目前没办法使用，后续有考虑升级吗

**Comment by 381924237** [comment]
就是内部的ui组件库中，一些跳转的行为，依赖的react router的版本是6.x，迁移到新的ssr项目中使用不了

**Comment by zhangyuang** [comment]
这是ui组件自己的问题，没有支持的计划。我不认为ui组件的设计应该耦合依赖库的版本

**Comment by 381924237** [comment]
> 这是ui组件自己的问题，没有支持的计划。我不认为ui组件的设计应该耦合依赖库的版本

好的谢谢
