### ISSUE TITLE
后续会考虑支持嵌套路由吗？

### ISSUE THREAD

**Issue by WadeZhu** [ykfe/ssr#277]
## 详细描述你的问题
后续会考虑支持嵌套路由吗？

**Comment by zhangyuang** [comment]
不考虑支持，翻过去的issue在业务代码中完全可以自行实现嵌套路由的功能

**Comment by WadeZhu** [comment]
过去的issue中推荐用react-router-config来自行实现，请问在vue3的项目中有什么库推荐用来自行实现嵌套路由吗？

**Comment by zhangyuang** [comment]
没推荐过用react-router-config实现啊…我一直说的都是不需要第三方库纯业务代码实现

**Comment by WadeZhu** [comment]
尝试了自己写route.ts 加了个children
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/20967647/229668064-8d2d40c7-e9bf-4787-9586-a384e94d1c7b.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/20967647/229668151-7c0c6504-9868-40fd-8f55-73a3af1efbef.png">
但是报错
<img width="535" alt="image" src="https://user-images.githubusercontent.com/20967647/229668186-0ca2e6bf-e5fb-489d-a2fa-69b12a9c4105.png">
问题和这个issue提出的https://github.com/zhangyuang/ssr/issues/102 一样
<img width="943" alt="image" src="https://user-images.githubusercontent.com/20967647/229668465-12e76b41-e0aa-412b-acfa-a9f571843145.png">
findRoute查不到children导致解构赋值报错

纯代码实现嵌套路由是指这样做吗？

**Comment by zhangyuang** [comment]
选项一给他配置fetch
选项二嵌套路由本质就是url映射到组件。使用render.vue纯业务代码就能实现，无需任何框架层面的支持

**Comment by zhangyuang** [comment]
哦不对 这里find的时候不会去查询children，所以直接用选项二

**Comment by WadeZhu** [comment]
选项一，可以再加一个一级路由上面加个fetch

**Comment by WadeZhu** [comment]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/20967647/229676972-60aa09ca-90d6-45bc-a6c0-2bcebb2773d8.png">

**Comment by zhangyuang** [comment]
你能跑通就行虽然我觉得完全没有必要依赖vue框架的这种写法来实现嵌套路由功能。只在vue文件里很轻易的就能实现

**Comment by WadeZhu** [comment]
选项二
<img width="774" alt="image" src="https://user-images.githubusercontent.com/20967647/229677034-f24127aa-caef-42bf-8636-a55b4ba99594.png">
像这种效果，是要每个url对应的组件都引入一个user组件再写对应组件逻辑吗？还有怎么做到页面无刷新切换profile和post

**Comment by zhangyuang** [comment]
在 johny/*对应的组件中使用component：is动态加载children组件

**Comment by WadeZhu** [comment]
profile下面再有嵌套路由的话就很难维护这个根据url选择对应组件来渲染的逻辑了，而且模块懒加载也很难做

**Comment by zhangyuang** [comment]
难不难维护完全取决于你代码怎么抽象。
懒加载用promise的形式导入就行了

**Comment by zhangyuang** [comment]
尝试了一下，在Vue场景下框架层支持嵌套路由能力不难实现，所以这里在框架层支持了vue场景下的嵌套路由

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$feRoutes#%E6%89%8B%E5%8A%A8%E7%BC%96%E5%86%99%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/17424434/229753243-c448f141-a938-4cd2-b157-998ba69bed91.png">
