### ISSUE TITLE
setHeader error in bigpipe mode when second render

### ISSUE THREAD

**Issue by MervynFang** [ykfe/ssr#285]
https://github.com/zhangyuang/ssr/blob/859d35ddf5ef17e4ed9fe2dfb215c53e7542bea0/packages/utils/src/server/runtime.ts#L12

nestjs + vue3

开启 `bigpipe` 模式，第二次调用 `render`，`runtime` `setHeader` 报错，如下图，这里是否应为
```js
!(ctx as FastifyContext).response.headersSent
```

<img width="1279" alt="Snipaste_2023-05-11_16-39-48" src="https://github.com/zhangyuang/ssr/assets/8202702/bb04efe7-96f9-4f19-9b44-543ef41c6b52">

**Comment by zhangyuang** [comment]
你用的是fatify?

**Comment by MervynFang** [comment]
不是呀，用 nestjs

**Comment by zhangyuang** [comment]
nestjs底层是基于express或fatify的啊=。= 问你选的是哪个

**Comment by MervynFang** [comment]
express，你是说 fastify ？😂
