### ISSUE TITLE
我的可以路由同构，然后不需要修改什么配置可以自由切换csr和ssr，然后可以webpack 构架微服务吧。不知道你那有没这功能>

### ISSUE THREAD

**Issue by ygs-code** [ykfe/ssr#289]
> 

差别是啥？为啥又需要重新写一个呢？

_Originally posted by @i5ting in https://github.com/zhangyuang/ssr/issues/19#issuecomment-1556477301_

**Comment by zhangyuang** [comment]
有需求可以直接在原issue回复，不要重新开issue

**Comment by zhangyuang** [comment]
另外不知道你说的路由同构具体指什么，自由切换csr和ssr本框架已经支持。`可以webpack 构架微服务吧`你说的是微服务还是微前端，微前端本框架也已经支持接入
