### ISSUE TITLE
请问如何实现类似nextjs中的refetch能力，可以让页面主动触发fetch方法？

### ISSUE THREAD

**Issue by JasonJ1220** [ykfe/ssr#290]
如题！或者目前的最佳实践是什么？

**Comment by zhangyuang** [comment]
自己在组件中import fetch文件 再手动调用？

**Comment by JasonJ1220** [comment]
我们是否也可以考虑使用类似：
history.replace(location.pathname + '?t=' + Date.now());
这样的做法？

**Comment by zhangyuang** [comment]
可以试试，理论上不要用这种方法，应该是行不通的，react只会在组件重新render的时候调用fetch，vue只会在router切换的时候调用

**Comment by JasonJ1220** [comment]
行不通的
您那边推荐的最佳实践就是手动引入fetch.ts再重新执行一下是吧？

**Comment by zhangyuang** [comment]
可以这么做没有任何问题

**Comment by JasonJ1220** [comment]
replace组件已经重新刷新了 会重新进入render 但不会进入fetch

**Comment by zhangyuang** [comment]
> replace组件已经重新刷新了 会重新进入render 但不会进入fetch

指的是销毁重新render才会fetch，事实上/detail/:id从 /detail/1跳转到 /detail/2也并不会触发销毁重新fetch
