### ISSUE TITLE
ssr build --optimize 运行报错

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#293]
运行ssr build --optimize 提示 build/generateMap.json 文件不存在

版本：
├─ ssr-common-utils@6.2.85
├─ ssr-core@6.2.22
├─ ssr-deepclone@1.0.1
├─ ssr-hoc-react18@6.2.11
├─ ssr-mini-css-extract-plugin@1.6.3
├─ ssr-plugin-midway@6.2.20
├─ ssr-plugin-react18@6.2.63
├─ ssr-serialize-javascript@6.0.4
├─ ssr-types@6.2.46
├─ ssr-vite-plugin-style-import@2.0.1
├─ ssr-webpack@6.2.11
├─ ssr-window@3.0.0
├─ ssr@6.2.48
├─ ssri@7.1.1
└─ webpack@4.46.0
   └─ ssri@6.0.2

**Comment by zhangyuang** [comment]
提供最简可复现仓库

**Comment by dean16930** [comment]
新项目使用仓库的最新版本 ssr start|build --optimize 选项来构建时，一直处于building状态（十几分钟了...），途中没有任何反馈，想问下是什么原因，如何跟踪这个状态

**Comment by zhangyuang** [comment]
> 新项目使用仓库的最新版本 ssr start|build --optimize 选项来构建时，一直处于building状态（十几分钟了...），途中没有任何反馈，想问下是什么原因，如何跟踪这个状态

<img width="635" alt="image" src="https://github.com/zhangyuang/ssr/assets/17424434/1837b3e9-f4dd-4313-a037-91cb7a474af6">
无法复现，新开issue提供完整复现步骤及环境
