### ISSUE TITLE
按照快速开始指南，部署到阿里云函数计算FC后，打开直接500

### ISSUE THREAD

**Issue by ldhlfzysys** [ykfe/ssr#294]
`
npm init ssr-app my-ssr-project
`
选择
`
midway-vue3-ssr
`
执行
`
npm deploy
`
部署成功
打开阿里云对应域名后显示Internal Server Error, real status: 500
使用域名后，报同样错误

本地可以成功打开模板，部署到

**Comment by ldhlfzysys** [comment]
本地和函数计算FC中node版本也一致

**Comment by ldhlfzysys** [comment]
去阿里云执行了一下，发现是Cannot find module 'pinia'

**Comment by zhangyuang** [comment]
手动在`dependencies`中添加 `pinia ` 模版稍后更新

**Comment by zhangyuang** [comment]
发现 `nestjs-vue3` 的模版加了，`midway-vue3`的没加，稍后更新一下

**Comment by ldhlfzysys** [comment]
感谢
