### ISSUE TITLE
好像不支持动态配置文件

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#295]
目录结构这边好像支持
<img width="1130" alt="image" src="https://github.com/zhangyuang/ssr/assets/21193805/a97f9df1-21a2-4122-9cf6-cd27a59a33bd">
但代码这边好像不支持这个逻辑
<img width="841" alt="image" src="https://github.com/zhangyuang/ssr/assets/21193805/95af7d58-7eef-4fe1-b73a-37c129272738">

版本：
├─ ssr-common-utils@6.2.85
├─ ssr-core@6.2.22
├─ ssr-deepclone@1.0.1
├─ ssr-hoc-react18@6.2.11
├─ ssr-mini-css-extract-plugin@1.6.3
├─ ssr-plugin-midway@6.2.20
├─ ssr-plugin-react18@6.2.63
├─ ssr-serialize-javascript@6.0.4
├─ ssr-types@6.2.46
├─ ssr-vite-plugin-style-import@2.0.1
├─ ssr-webpack@6.2.11
├─ ssr-window@3.0.0
├─ ssr@6.2.48
├─ ssri@7.1.1
└─ webpack@4.46.0
   └─ ssri@6.0.2

**Comment by zhangyuang** [comment]
运行时动态配置调用 render 方法时支持动态传入

**Comment by linchCN** [comment]
> 运行时动态配置调用 render 方法时支持动态传入

那请问build时要怎么区分。
比如我有3个不同的config。
<img width="232" alt="image" src="https://github.com/zhangyuang/ssr/assets/21193805/71e9cafd-bab5-4c64-897b-f36d0cb2991f">

**Comment by zhangyuang** [comment]
可以在同一文件中根据环境变量区分环境（本来就不推荐用多文件配置

**Comment by linchCN** [comment]
> 可以在同一文件中根据环境变量区分环境（本来就不推荐用多文件配置

好吧，我原来看你们那个目录结构以为是支持的
我现在自己在外面套了一层
<img width="636" alt="image" src="https://github.com/zhangyuang/ssr/assets/21193805/fc10b008-11ef-4924-88a5-809f218509fb">
