### ISSUE TITLE
Webpack最优化问题

### ISSUE THREAD

**Issue by lemondreamtobe** [ykfe/ssr#296]
非vite启动下，vendor5.8M呢 
然后看webpack还是v4
是否考虑过升到5呢？
还有怎么扩展webpack呢

**Comment by zhangyuang** [comment]
1、不考虑升 webpack5
2、扩展webpack参考 https://doc.ssr-fc.com/docs/api$config#chainBaseConfig%F0%9F%A4%94
3、webpack构建配置优化参考 https://doc.ssr-fc.com/docs/features$faq#%E9%AB%98%E6%80%A7%E8%83%BD%E4%BA%A7%E7%89%A9%E6%9E%84%E5%BB%BA , https://doc.ssr-fc.com/docs/api$config#extraJsOrder%F0%9F%A4%94
