### ISSUE TITLE
sourcemap 对应配置完善后，构建产物中未生成 sourcemap 文件

### ISSUE THREAD

**Issue by sunnywanggit** [ykfe/ssr#300]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
config.ts 配置：
```js
  chainBaseConfig: (chain) => {
    chain.devtool('source-map');
    ......
  })
```

生成代码：
![image](https://github.com/zhangyuang/ssr/assets/53786183/f7fc15b9-ac34-4c75-b8bb-e6eb7830914d)

## 期望的结果

正常生成 sourcemap 文件

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

```js
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ ssr-client-utils@6.2.7
├─ ssr-core-vue3@6.2.11
├─ ssr-deepclone@1.0.1
├─ ssr-hoc-vue3@6.2.0
├─ ssr-plugin-nestjs@6.2.10
├─ ssr-plugin-vue3@6.2.18
│  └─ ssri@7.1.1
├─ ssr-server-utils@6.2.17
├─ ssr-types@6.2.10
├─ ssr-webpack@6.2.10
├─ ssr@6.2.13
├─ ssri@8.0.1
└─ terser-webpack-plugin@1.4.5
   └─ ssri@6.0.2

```

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
不需要修改 chain, GENERATE_SOURCEMAP=1 ssr build，生产环境默认不生成sourcemap有造成源码泄漏的风险。有需求通过环境变量开启

**Comment by sunnywanggit** [comment]
@zhangyuang  好的 感谢
