### ISSUE TITLE
官网挂了，麻烦看一下

### ISSUE THREAD

**Issue by sunnywanggit** [ykfe/ssr#301]
## 详细描述你的问题
官网内容全部展示空白：
![image](https://github.com/zhangyuang/ssr/assets/53786183/6821465b-42e3-4339-8764-e04420385650)

## 期望的结果
官网内容正常展示。

**Comment by sunnywanggit** [comment]
@zhangyuang  另外想了解一下，接入 sentry 的话，对应的配置应该放在项目的哪个地方呢？

**Comment by zhangyuang** [comment]
app.vue

**Comment by zhangyuang** [comment]
文档已修复

**Comment by sunnywanggit** [comment]
@zhangyuang 感谢
