### ISSUE TITLE
ssr build 优化建议

### ISSUE THREAD

**Issue by jianlong1994** [ykfe/ssr#304]
docker 下进行编译时由于代码层面的错误导致 ssr build 失败时未触发 docker build 中断，因此以为 构建成功

ssr@6.2.46

**Comment by zhangyuang** [comment]
可以看看具体是什么类型的错误babel-loader处理的时候的错误码

**Comment by jianlong1994** [comment]
@zhangyuang 

### 错误原因
开发 import 自定义组件时路径的大小写错误引起的

### 目前情况
1. 在开发环境下可正确编译
2. 在`docker build`下可打包成功，`build` 目录下没有 `client` 和 `server` 两个目录
3. 在直接使用`node:14.17.6`镜像进行编译时有报错

### 错误截图
![image](https://github.com/zhangyuang/ssr/assets/26018866/da9ec226-24be-4538-967a-48ed68a09944)

### 开发环境：
> win10
> node v14.15.4

### 版本号：
```
+-- @babel/core@7.21.3
+-- @babel/preset-env@7.20.2
+-- @midwayjs/bootstrap@3.10.15
+-- @midwayjs/core@3.10.15
+-- @midwayjs/decorator@3.10.15
+-- @midwayjs/koa@3.10.15
+-- @midwayjs/mock@3.10.15
+-- ant-design-vue@3.2.15
+-- cross-env@7.0.3
+-- dayjs@1.11.7
+-- dotenv@16.0.3
+-- eslint-config-standard-vue-ts@1.0.21
+-- js-cookie@3.0.1
+-- jsencrypt@3.0.0-rc.1
+-- koa-static-cache@5.1.4
+-- lodash@4.17.21
+-- midway-schedule@2.15.0
+-- mitt@3.0.0
+-- pm2@4.5.6
+-- query-string@7.1.3
+-- ssr@6.2.46
+-- ssr-core-vue3@6.2.21
+-- ssr-hoc-vue3@6.2.0
+-- ssr-plugin-midway@6.2.20
+-- ssr-plugin-vue3@6.2.83
+-- ssr-server-utils@6.2.69
+-- ssr-types@6.2.42
+-- swiper@8.4.7
+-- typescript@4.9.5
+-- vant@4.3.1
+-- vue@3.2.38
+-- vue-clipboard3@2.0.0
+-- vue-lazyload@3.0.0-rc.2
+-- vue-router@4.1.6
+-- vuex@4.1.0
`-- xlsx@0.18.5
```

### Dockerfile 示例
```Dockerfile
FROM node:14.17.6 as BUILD

WORKDIR /build

COPY .npmrc .
COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build
```

**Comment by zhangyuang** [comment]
已修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianlong1994 ***@***.***&gt;
发送时间: 2023年8月3日 09:39
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] ssr build 优化建议 (Issue #304)





 
错误原因
 
开发 import 自定义组件时路径的大小写错误引起的
 
目前情况
  
在开发环境下可正确编译
 
在docker build下可打包成功，build 目录下没有 client 和 server 两个目录
 
在直接使用node:14.17.6镜像进行编译时有报错
  
错误截图
 

 
开发环境：
  
win10
 node v14.15.4
  
版本号：
 +-- @***@***.*** +-- @***@***.*** +-- @***@***.*** +-- @***@***.*** +-- @***@***.*** +-- @***@***.*** +-- @***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** +-- ***@***.*** `-- ***@***.***  
Dockerfile 示例
 FROM node:14.17.6 as BUILD WORKDIR /build COPY .npmrc . COPY package.json . COPY package-lock.json . RUN npm ci COPY . . RUN npm run build
