### ISSUE TITLE
框架怎么设置 productionSourceMap

### ISSUE THREAD

**Issue by qc5926** [ykfe/ssr#306]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
代码编译后无法无法在浏览器中打断点调试

## 期望的结果
可以在浏览器中找到源码

## 当前使用的版本
 V6.0.0
`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
自行在issue列表中搜索关键字



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qc5926 ***@***.***&gt;
发送时间: 2023年8月17日 09:38
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 框架怎么设置 productionSourceMap (Issue #306)





 
提问前请确认以下几点信息，否则你的问题将不会被解答
  
参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
 
确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
 
对应服务端框架的使用问题请去它们的官方文档找答案。例如 Midway, Nest.js
 
如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
 
原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。
  
详细描述你的问题
 
代码编译后无法无法在浏览器中打断点调试
 
期望的结果
 
可以在浏览器中找到源码
 
当前使用的版本
 
V6.0.0
 不要贴 package.json 用 yarn list "ssr*"  来查看版本。同时建议熟读semver 规则并且知道怎么安装最新依赖！
 
复现仓库地址
 
超过一行代码能描述的问题必须提供复现地址, 用默认的 example 给最简单的复现代码不要给包含着一堆业务代码的仓库
 
你本人对问题可能的原因判断(如果你能大概判断的话)

**Comment by zhangyuang** [comment]
https://doc.ssr-fc.com/docs/features$faq#%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E7%94%9F%E6%88%90%20sourcemap

**Comment by qc5926** [comment]
好的，谢谢大佬
