### ISSUE TITLE
vite编译超时

### ISSUE THREAD

**Issue by juukee** [ykfe/ssr#307]
![image](https://github.com/zhangyuang/ssr/assets/28680837/1c929f75-81ce-42af-9fce-0ee6fe7b3968)
![1692778110412](https://github.com/zhangyuang/ssr/assets/28680837/1f08758f-b4b6-4b42-a606-1b05c193a566)
vite编译时看起来有问题，设置了8秒超时，还是不行，内置vite版本2.9.16也比较低

**Comment by juukee** [comment]
```
npm run build:vite
```
运行这个命令可以解决问题

**Comment by juukee** [comment]
![1692779269438](https://github.com/zhangyuang/ssr/assets/28680837/24fca90d-9181-4b2f-b1db-b056deb10d0b)
会出现以上提醒，想要去除
![1692779311457](https://github.com/zhangyuang/ssr/assets/28680837/6dd0587a-ba62-4629-a7f7-0e3085e044c2)

**Comment by zhangyuang** [comment]
1、npm run build:vite和设置isvite: true没有区别。
2、vite版本没有升级的计划
3、移除tsconfig的paths字段就行了
