### ISSUE TITLE
怎么引入element-plus

### ISSUE THREAD

**Issue by pakkery** [ykfe/ssr#308]
怎么引入element-plus

**Comment by zhangyuang** [comment]
有问题就给复现

**Comment by pakkery** [comment]
你好,我想试试这个框架引用elemen跑起来后项目还是不能使用该ui
![image](https://github.com/zhangyuang/ssr/assets/63911888/541fb8d6-9994-4325-b3eb-e7105606a641)

**Comment by zhangyuang** [comment]
https://doc.ssr-fc.com/docs/features$faq#element-plus

**Comment by pakkery** [comment]
我尝试过但不知道为什么不行,还望指点一二,谢谢
![image](https://github.com/zhangyuang/ssr/assets/63911888/2f80e55a-2f2b-4d36-817d-d8f5922f5c9e)

**Comment by pakkery** [comment]
补充一下图片
![image](https://github.com/zhangyuang/ssr/assets/63911888/c6f4f477-201e-4492-baea-ac0e257ece83)

**Comment by zhangyuang** [comment]
给上下文给复现啊，如果你用的是vite那就手动导入elbutton啊

**Comment by pakkery** [comment]
![image](https://github.com/zhangyuang/ssr/assets/63911888/adaccf8f-e756-41d2-ac8d-80e005ec7b00)

**Comment by pakkery** [comment]
用了这个命令启动

**Comment by zhangyuang** [comment]
文档写的很清楚了啊，vite element-plus手动导入

**Comment by pakkery** [comment]
能不能全局引入这个ui,不用单个组件的引入

**Comment by zhangyuang** [comment]
这跟ssr框架没有任何关系，自行搜索vue怎么全局注册组件

**Comment by pakkery** [comment]
好的谢谢,再请问一下项目nestjs-vue3-ssr-pinia的端口怎么修改

**Comment by zhangyuang** [comment]
看文档 config.serverPort



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Pakkey ***@***.***&gt;
发送时间: 2023年8月25日 17:47
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么引入element-plus (Issue #308)





 
好的谢谢,再请问一下项目nestjs-vue3-ssr-pinia的端口怎么修改

**Comment by pakkery** [comment]
我在项目中没找到config.serverPort这个文件或者有关的字段
