### ISSUE TITLE
通过 less loader 配置的 less 变量不生效

### ISSUE THREAD

**Issue by hululuuuuu** [ykfe/ssr#309]
## 详细描述你的问题
在 config.ts 配置 如下
<img width="543" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/33e829fb-c769-4391-9ef9-98c4c26dbee1">
在 web/pages/index/index.less 使用
<img width="426" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/b5f7dbbb-a063-4d32-9f91-2a20a7bb8d6e">
结果是报错
![image](https://github.com/zhangyuang/ssr/assets/25917806/908a6488-5395-4af7-88aa-387c0f9bf768)

@primaryColor  和 @primary-color 都试过了，用了 ant-design-vue4.x 不过感觉不是这个问题，和业务也没有关系 因为项目是刚搭建的就没有写业务
 
## 期望的结果
 html视图对应相应的颜色

## 当前使用的版本
![image](https://github.com/zhangyuang/ssr/assets/25917806/4cd42e08-89c9-4f17-aed2-f9611e2c594a)

**Comment by zhangyuang** [comment]
可能得下周看看了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gxs ***@***.***&gt;
发送时间: 2023年9月15日 15:15
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 通过 less loader 配置的 less 变量不生效 (Issue #309)





 
详细描述你的问题
 
在 config.ts 配置 如下
 
 在 web/pages/index/index.less 使用
 
 结果是报错
 
 
@primarycolor  和 @primary-color 都试过了，用了 ant-design-vue4.x 不过感觉不是这个问题，和业务也没有关系 因为项目是刚搭建的就没有写业务
 
期望的结果
 
html视图对应相应的颜色
 
当前使用的版本

**Comment by hululuuuuu** [comment]
OK ，下周再看也不急
更详细的报错大概是这样的，我一开始怀疑是 vite ，不过我看文档config.ts 暴露的可配置接口只有这些，就没深入了
<img width="1089" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/1ef2bb1a-fc9a-4a22-9dfb-8938a0e018e0">

**Comment by zhangyuang** [comment]
vite场景用法如下

```js
import type { UserConfig } from 'ssr-types'

const userConfig: UserConfig = {
  css: () => {
    return {
      loaderOptions: {
        less: {
         
          modifyVars: {
            'primary-color': '#000'
          }
        }
      }
    }
  }
}

export { userConfig }

```

**Comment by zhangyuang** [comment]
最新版本兼容lessOptions入参

**Comment by hululuuuuu** [comment]
OK 我这边试过了 没问题。
