### ISSUE TITLE
请问有没有 egg的服务端插件？ 如果没有，后端想使用egg，该怎么做呢，谢谢。

### ISSUE THREAD

**Issue by shuangguo3** [ykfe/ssr#310]
请问有没有 egg的服务端插件？ 如果没有，后端想使用egg，该怎么做呢，谢谢。

**Comment by zhangyuang** [comment]
没有，直接用midway/nest这是目前最流行的服务端框架，想使用egg可以考虑自行接入。ssr框架并不绑定服务端框架

**Comment by shuangguo3** [comment]
如果自行接入的话，是使用服务端插件机制吧，有没有详细介绍该如何做的文档呢？

**Comment by zhangyuang** [comment]
自行参考已有的插件内容，or 使用midway/egg。不建议继续使用egg

**Comment by shuangguo3** [comment]
插件的实现是比较简单，关键不知道该怎么集成到项目里。
`// plugin-midway
import { start } from './start'
import { build } from './build'
import { deploy } from './deploy'

export function midwayPlugin () {
  return {
    name: 'plugin-midway',
    start,
    build,
    deploy
  }
}`

**Comment by zhangyuang** [comment]
你可以直接用midway+egg
