### ISSUE TITLE
生产环境的antdv ui css 样式和开发环境不一致

### ISSUE THREAD

**Issue by hululuuuuu** [ykfe/ssr#313]
## 大前提
我在layout/app.vue 里面引用了 antdv 相关 css
<img width="1131" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/557c229a-57dd-42c1-aa92-a4a33859a340">
并且我在 common.less 对 antdv 的 upload 组件设置了 css border:0;
<img width="1019" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/1387a338-efae-4760-93e2-1938754652fc">
##  我的问题
本地开发视图展示正常
<img width="1131" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/b9e153f7-c54a-472d-b2c1-c306cd5dcf31">

然后是生产环境 执行 npm run prod ("prod": "ssr build --vite && pm2 start pm2.config.js")
访问之后 border:0 这条 css 被覆盖了
<img width="1498" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/d5d66820-7326-468d-a372-827a3f422311">
这是我的 config.ts 的配置
<img width="755" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/93032c50-e3b8-44f9-9358-c869928eca6b">

## 期望的结果
开发环境和生产环境效果保持一致即可。我的理解是 同样一份代码打包之后 无论表现出 border:0 还是 border:1 ，生产环境和开发环境效果要一致

## 当前使用的版本
![image](https://github.com/zhangyuang/ssr/assets/25917806/54a6b222-fb09-4b7f-a95f-7ca56cd2935b)
antdv 版本：3.2.30
## 判断
打包过程中怀疑 antdv  css 加载顺序降到了 common.less 的下方导致的。

**Comment by zhangyuang** [comment]
请提供最简复线仓库



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gxs ***@***.***&gt;
发送时间: 2023年11月8日 10:43
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 生产环境的antdv ui css 样式和开发环境不一致 (Issue #313)





 
大前提
 
我在layout/app.vue 里面引用了 antdv 相关 css
 
 并且我在 common.less 对 antdv 的 upload 组件设置了 css border:0;
 
 
我的问题
 
本地开发视图展示正常
 
 
然后是生产环境 执行 npm run prod ("prod": "ssr build --vite &amp;&amp; pm2 start pm2.config.js")
 访问之后 border:0 这条 css 被覆盖了
 
 这是我的 config.ts 的配置
 
 
期望的结果
 
开发环境和生产环境效果保持一致即可。我的理解是 同样一份代码打包之后 无论表现出 border:0 还是 border:1 ，生产环境和开发环境效果要一致
 
当前使用的版本
 

 antdv 版本：3.2.30
 
判断
 
打包过程中怀疑 antdv  css 加载顺序降到了 common.less 的下方导致的。

**Comment by hululuuuuu** [comment]
@zhangyuang   好的 复现仓库等 最晚明天提供给你。这个因为是需要打包的 可能需要在本地运行，我这边直接新开个 git 仓库给你可以吗？

**Comment by zhangyuang** [comment]
可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gxs ***@***.***&gt;
发送时间: 2023年11月8日 11:38
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 生产环境的antdv ui css 样式和开发环境不一致 (Issue #313)





 
@zhangyuang   好的 复现仓库等 最晚明天提供给你。这个因为是需要打包的 可能需要在本地运行，我这边直接新开个 git 仓库给你可以吗？

**Comment by zhangyuang** [comment]
fix by utils@6.2.112
