### ISSUE TITLE
引入 css文件 报错

### ISSUE THREAD

**Issue by hululuuuuu** [ykfe/ssr#314]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题
按照官方教程
https://swiperjs.com/vue#usage

就两行代码 引入
<img width="610" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/ec9e0e3f-5d46-400e-8816-0ba59407351a">
然后报错
<img width="1033" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/e265c6e7-ffe6-442a-badf-e0ce47d3760b">

我后面配置了一下 config.ts
<img width="566" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/0b28ac15-b794-457d-8758-9c533248e776">
依然有同样的问题
不知道是我哪里配置的不对 还是有别的解决方案

## 期望的结果
希望可以直接引入

## 当前使用的版本
<img width="720" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/f0c79897-da97-41f9-8bac-fadcc4c35bbb">

**Comment by zhangyuang** [comment]
whitelist添加/swiper\.css/

**Comment by hululuuuuu** [comment]
<img width="692" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/5525116c-0214-4f3e-88cb-8612b195fd3a">
加了之后 还是一样的错误
<img width="704" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/6e59c022-bb05-42e2-b180-4925481579de">

下面是 swiper 的结构目录
<img width="401" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/83388d9d-48aa-460e-b77e-3d3b6627ab88">
以及 swiper 的 package.json
<img width="1003" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/a11f7c38-813c-4441-852c-86cb81ccf7ed">

**Comment by hululuuuuu** [comment]
新搭建的项目，确定错误就在
import "swiper/css";
删掉这行就好了

**Comment by zhangyuang** [comment]
仔细阅读文档

whiteList:[/swiper\.css/]
不要新增rule

**Comment by hululuuuuu** [comment]
我看了下文档，我理解 whiteList的作用，然后我把刚把cssOptions 这块儿删了，并且新增了  whiteList: [/swiper.css/]。重新启动项目，依然还是这个错误。不知道是不是我理解错了你的意思，加错地方了？
<img width="697" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/b4cd6622-bcc3-4224-9373-bd1d2d840779">

**Comment by zhangyuang** [comment]
vite场景配置 ` whiteList: [/swiper/]`

**Comment by hululuuuuu** [comment]
@zhangyuang  那你也泰裤辣，解决了。

**Comment by zhangyuang** [comment]
顺便这里建议一下不要用`import 'swiper/css'` 改为 `import 'swiper/swiper.min.css'`。以适配webpack4以及更好的兼容性

**Comment by hululuuuuu** [comment]
OK OK 感谢感谢

**Comment by hululuuuuu** [comment]
大佬 本来不想打搅你的，不过发现 npm run start:vite 执行没问题，但是 npm run prod 会提示
<img width="1357" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/73488816-a128-4a09-8b50-5aad3998c064">
还是这个配置 config.ts
whiteList: [/swiper/] 
还是这样的引入 
<img width="795" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/3755f3ee-34f0-4cdd-b544-82fdd9294d75">
这些都没变
@zhangyuang

**Comment by hululuuuuu** [comment]
我知道问题了, 需要加入 ssr build --vite  之前是 ssr build .

**Comment by zhangyuang** [comment]
上面说了改引入方式啊

**Comment by hululuuuuu** [comment]
我改了引入方式 会报错。因为项目比较急 我就没有过度纠结这个问题，等下我改一下 给你看看

**Comment by hululuuuuu** [comment]
在只改变引入方式的情况下 
config.ts 如下
  whiteList: [/swiper/],
执行 npm run start:vite 会出现如下问题
<img width="1142" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/7408a4a2-4f0f-4be6-8ed0-a16497525f4a">
如果执行 npm run start
<img width="1444" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/b83ae376-2c2f-4e7a-99e6-644c2769f8df">
<img width="654" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/9f8babc7-52be-4217-aa01-77cb9f8e21a9">
则会出现更多的其他问题，因为我们项目已经在迭代中了，所以不能再回头大幅修改引入方式。所以只能这样了 @zhangyuang  再次感谢

**Comment by zhangyuang** [comment]
swiper/vue的引入方式也改啊

**Comment by hululuuuuu** [comment]
可是我想用 vite 。  npm run start:vite   会出现 Missing "./swiper.min.css" export in "swiper" package 
<img width="924" alt="image" src="https://github.com/zhangyuang/ssr/assets/25917806/4ba393e4-d2c5-4215-9bb6-c8c99bd0f1d7">
我偏向于 vite 启动整个环节都是 vite，以后再用您的项目模板也会这样。

**Comment by zhangyuang** [comment]
那你继续用这种写法吧，webpack4不支持package.json export,或者换成example用的6.x版本的swiper
