### ISSUE TITLE
请问启动后，isBrower找不到，编译报错怎么解决？谢谢

### ISSUE THREAD

**Issue by perchecc** [ykfe/ssr#316]
## 详细描述你的问题
![image](https://github.com/zhangyuang/ssr/assets/17824405/04cf575f-351e-4f24-b0a1-07bd6dfb7c7b)

## 期望的结果
项目运行正常

## 当前使用的版本

nodejs18.19.0
vue3

## 复现仓库地址

[ssr-vue-antd.zip](https://github.com/zhangyuang/ssr/files/13858410/ssr-vue-antd.zip)

## 你本人对问题可能的原因判断(如果你能大概判断的话)

不知道为什么，文档里是这么解释的
![image](https://github.com/zhangyuang/ssr/assets/17824405/0b66a6a8-259b-429a-aed3-766f82eefd51)

https://doc.ssr-fc.com/docs/features$fetch#%E5%88%A4%E6%96%AD%E5%BD%93%E5%89%8D%E7%8E%AF%E5%A2%83

**Comment by zhangyuang** [comment]
删除.browserslistrc，另外没看懂这里为什么又要自己装一堆babel依赖，以及为什么要把版本号全部去掉

**Comment by perchecc** [comment]
> 删除.browserslistrc，另外没看懂这里为什么又要自己装一堆babel依赖，以及为什么要把版本号全部去掉

好的，可行！感谢~

![image](https://github.com/zhangyuang/ssr/assets/17824405/c5015952-494f-4f5a-aed9-26b9006ec3ee)
版本号去掉？没有发现在哪里。
3Q
