### ISSUE TITLE
npx ssr build --html 编译出错

### ISSUE THREAD

**Issue by tianbaolin** [ykfe/ssr#317]
使用 `npx ssr build --html `构建时 爆出错误 ：
```
Generating html file...                                                                                                  14:03:21
The argument 'id' must be a non-empty string. Received ''
```
生成html文件失败了。追踪了一下错误，原来是html.js 这个文件里面有这样一行代码：

`const { h, Fragment } = await import(loadModuleFromFramework('vue'))`

我是用的react框架，怎么执行到这儿来了。把上面代码`loadModuleFromFramework`方法的传参`vue`改为`react`就生成html成功了。能这样改吗？更好的解决方案是啥？

**Comment by zhangyuang** [comment]
support `ssr build --html` in react by ssr@6.2.67
