### ISSUE TITLE
build:o 相关问题

### ISSUE THREAD

**Issue by dean16930** [ykfe/ssr#322]
新项目使用仓库的最新版本 ssr start|build --optimize 选项来构建时，一直处于building状态（十几分钟了...），途中没有任何反馈，想问下是什么原因，如何跟踪这个状态

## 当前使用的版本

dependencies:
ssr-common-utils 6.2.116
ssr-core 6.2.29
ssr-hoc-vue3 6.2.0

devDependencies:
ssr 6.2.67
ssr-plugin-midway 6.2.22
ssr-plugin-vue3 6.2.102
ssr-types 6.2.52

**Comment by zhangyuang** [comment]
ssr-common-utils@6.2.120 最新版本尝试修复了，可以再试试。还不行的话，启动的时候加上环境变量
```bash
$ DEBUG=ssr npx ssr build -o
```
并截图日志

**Comment by dean16930** [comment]
更新了版本，到这里就不动了
![1709199428445](https://github.com/zhangyuang/ssr/assets/48011106/7f53ad03-3253-4072-a0f2-64f27142f4d6)

**Comment by zhangyuang** [comment]
不用pnpm试试

**Comment by dean16930** [comment]
> ssr-common-utils@6.2.120 最新版本尝试修复了，可以再试试。还不行的话，启动的时候加上环境变量
> 
> ```shell
> $ DEBUG=ssr npx ssr build -o
> ```
> 
> 并截图日志



> 不用pnpm试试

用yarn试了下，同样到这个包的位置就卡出了

**Comment by zhangyuang** [comment]
截图日志看看

**Comment by dean16930** [comment]
> 截图日志看看

下面是yarn（跟上面截图一样），试npm也一样
![1709546570876](https://github.com/zhangyuang/ssr/assets/48011106/fc395ced-b043-470f-8ab2-260c6f95c5a4)

**Comment by zhangyuang** [comment]
你用了ant-design啊。。。又说是新创建的项目。给复现仓库

**Comment by dean16930** [comment]
> 你用了ant-design啊。。。又说是新创建的项目。给复现仓库

是新项目，但已经上线，vendor有点大，所以想尝试用框架提供的optimize优化下

**Comment by zhangyuang** [comment]
提供最简复现吧，不然没法看原因
