### ISSUE TITLE
请教下如何将node_module依赖构建到产物中，从而减少远端部署文件大小

### ISSUE THREAD

**Issue by JesseHooo** [ykfe/ssr#329]
问题：npm run build:vite 之后发现 /dist 和 /build路径下文件仍有依赖/node_modules的。
期望：希望将node_modules中需要的部分构建到产物中，应该如何操作。

复现：
1.拉项目
2.npm i
3.npm run build:vite
4.npm i pm2 -g
5.复制
 ./build
./dist
./package.json
./node_module
./pm2.config.js
./config.ts
到另一个空文件夹下，并在此执行 pm2 start ./pm2.config.js，服务运行成功
6.删除./node_module后重启则服务运行失败

附图:
![image](https://github.com/zhangyuang/ssr/assets/49136862/6d20affe-8569-48db-a16f-23f67be325c6)

**Comment by zhangyuang** [comment]
参考 https://doc.ssr-fc.com/docs/api$config#whiteList%F0%9F%A4%94
