### ISSUE TITLE
vue3 ssr项目中部分场景下使用扩展运算符，在vite build之后产生报错

### ISSUE THREAD

**Issue by JesseHooo** [ykfe/ssr#331]
## 详细描述你的问题
使用nestjs-vue3-ssr-pinia模板初始项目，在vue文件中，已发现在对ref、computed、route.query中的数组使用扩展运算符时，dev时候正常运行，build后产生异常报错

## 期望的结果
期望对于该报错dev和build保持一致，并且请教如何解决此问题

## 当前使用的版本
"ssr": "^6.0.0"

## 具体复现
1.nestjs-vue3-ssr-pinia模板初始项目，配置为isVite
2.修改\web\pages\index\render.vue
![image](https://github.com/zhangyuang/ssr/assets/49136862/281e7a43-f5b2-403a-af9d-3abc1337edbf)
3.npm start 无报错
4.npm run build
5.pm2 start ./pm2.config.js
6.访问出现报错

## 你本人对问题可能的原因判断(如果你能大概判断的话)
对于普通数组使用[...arr]是没问题的，问题出现于vue ref相关的api使用[...arr]时
报错描述的应该是在defineComponent是发生错误
![image](https://github.com/zhangyuang/ssr/assets/49136862/5cebc678-5db8-49e0-8a3a-79ee8edfd326)

**Comment by zhangyuang** [comment]
无法复现，请直接提供复现仓库

**Comment by JesseHooo** [comment]
> 无法复现，请直接提供复现仓库

https://github.com/JesseHooo/ssr-nestjs-vue3-demo

**Comment by zhangyuang** [comment]
同样无法复现，建议检查自身的开发环境以及提供完整的错误信息

**Comment by zhangyuang** [comment]
你把lock文件也提交上来吧

**Comment by JesseHooo** [comment]
> 你把lock文件也提交上来吧

提交上去了，还是那个仓库

**Comment by JesseHooo** [comment]
补充 win11 AMD64，尝试过切换node版本重新构建运行仍未解决

**Comment by JesseHooo** [comment]
补充2：
1.用了另一台笔记本AMD64win11 node18 -- 没复现
2.用没复现的lock放到原本电脑上重新安装、构建、运行 -- 仍然复现
3.用了同事的电脑AMD64 win10 node18 -- 复现
4.用linux服务器x86_64 node16 --复现
5.朋友mac m2 拉demo 执行prod -- 没复现
目前对报错复现规律有点迷
具体报错信息：
![de4784d2bee9b0f7b24879970ebb1d6](https://github.com/zhangyuang/ssr/assets/49136862/fed29ee8-2c72-4e8d-b3b2-cc6c7d42f3d2)
![6f188c7ebe60661ce79cd74731ac2cd](https://github.com/zhangyuang/ssr/assets/49136862/cad98db7-0d29-4c8b-ad3e-ca5502584568)
![1718955684993(1)](https://github.com/zhangyuang/ssr/assets/49136862/82f583a7-15f0-4648-9d42-345553a90a79)

**Comment by zhangyuang** [comment]
node_modules和构建后的build文件夹一起提交上来吧

**Comment by JesseHooo** [comment]
> node_modules和构建后的build文件夹一起提交上来吧

提交了，麻烦大佬了

**Comment by zhangyuang** [comment]
你上传的node_modules无法直接运行，不过根据build里面的内容尝试修复了一下。删掉lock使用最新依赖ssr-common-utils@6.2.131试试

**Comment by JesseHooo** [comment]
试了几次还是一样报错

**Comment by JesseHooo** [comment]
更新依赖后确实没报错了，但是操作第二次的时候依赖更新了但报错仍复现。
复现仓库更新：main分支是ok的，demo2分支是仍复现的。(现在把所有gitignore取消了)

**Comment by zhangyuang** [comment]
报错信息贴出来，另外最新版本支持ssr build --nominify --vite支持构建未混淆的文件来查看报错信息

**Comment by JesseHooo** [comment]
报错基本是和上面的一样的

![企业微信截图_17192812977292](https://github.com/zhangyuang/ssr/assets/49136862/e9dc060b-1980-4dac-963f-0d9443f1f1ed)

![企业微信截图_17192815272312](https://github.com/zhangyuang/ssr/assets/49136862/97e0f7e3-4bc7-4bd4-877d-bb67cdce1f0d)

目前是通过避开该写法，避免报错
![企业微信截图_17192812806626](https://github.com/zhangyuang/ssr/assets/49136862/213542e4-5500-4aa7-b0ef-b848bbeb93b3)

早上试了之后demo仓库的代码基本不复现了，但自己开发的代码还是会出现，我再观察一下吧，感谢大佬的耐心
