### ISSUE TITLE
vue3 使用vite构建时，能否支持 .dev.env|.stage.env|.prod.env 多环境配置

### ISSUE THREAD

**Issue by hyflzh1314** [ykfe/ssr#332]
ssr build --vite --mode stage ，ssr build --vite --mode prod 通过不同命令读取不同环境的env文件配置信息

**Comment by zhangyuang** [comment]
最新版本支持 `ssr start/build --vite --viteMode xxx`

**Comment by hyflzh1314** [comment]
好的，感谢
