### ISSUE TITLE
大佬您好， 我需要在window上挂载新的属性， 请问有什么方式吗？

### ISSUE THREAD

**Issue by yushuRo** [ykfe/ssr#336]

**Comment by zhangyuang** [comment]
layout组件中自行生成script标签内容



发自我的iPhone


------------------ 原始邮件 ------------------
From: yushuRo ***@***.***&gt;
发送时间: 08/23/2024, 20:21
To: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/ssr] 大佬您好， 我需要在window上挂载新的属性， 请问有什么方式吗？ (Issue #336)
