### ISSUE TITLE
内部有cheerio包, 要求node的18.17版本, 公司内部自动化都使用的16版本, 会报错

### ISSUE THREAD

**Issue by xiaokyo** [ykfe/ssr#339]
## 详细描述你的问题
yarn install 不能使用node16版本, 必需要18.17版本以上
ssr-core内部有个cheerio依赖, 配置了必需使用18.17, 这个包能否去除, 配置是否能降低node版本依赖

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/a1185e47-ef20-4fca-b376-69dff195c6ee">

<img width="780" alt="image" src="https://github.com/user-attachments/assets/173a579e-48e2-4504-95ab-dcee1b02fc18">

## 期望的结果
能使用node16版本下依赖

## 当前使用的版本

<img width="877" alt="image" src="https://github.com/user-attachments/assets/cf437dd2-cfe8-4c76-a8ab-2f9b2ca22554">

## 复现仓库地址
无

## 你本人对问题可能的原因判断(如果你能大概判断的话)
cheerio包内部依赖的node版本配置是否可以改动成16+

**Comment by xiaokyo** [comment]
好像只会在yarn的时候报错, npm install可以正常下载

**Comment by zhangyuang** [comment]
不再建议使用 Node.js v16，绝大多数模块已不再支持。临时解决使用以下命令
```
$yarn install --ignore-engines
```

**Comment by xiaokyo** [comment]
> 不再建议使用 Node.js v16，绝大多数模块已不再支持。临时解决使用以下命令
> 
> ```
> $yarn install --ignore-engines
> ```

好
