### ISSUE TITLE
重新安装依赖，ts错误

### ISSUE THREAD

**Issue by nead3009** [ykfe/ssr#343]
## 详细描述你的问题
nextjs + vue3项目，删除项目node_modules和yarn.lock，重新安装依赖，开发环境yarn start运行项目后（没有用vite）大量ts错误，问下这个怎么解决

![image](https://github.com/user-attachments/assets/944f2c72-8328-465a-9ea3-f4c67b3e090e)
![image](https://github.com/user-attachments/assets/e99c703e-3816-46ed-88eb-79af92e1f2f9)
![image](https://github.com/user-attachments/assets/c4386459-bd4d-4772-8e29-6adfb53327e8)
![image](https://github.com/user-attachments/assets/7315c4df-1d3e-43b4-b6ec-d54640370e4b)

## 当前使用的版本
warning package.json: "dependencies" has dependency "eslint" with range "^8.35.0" that collides with a dependency in "devDependencies" of the same name with version "^8.34.0"
warning nestjs-vue3-ssr@1.0.0: "dependencies" has dependency "eslint" with range "^8.35.0" that collides with a dependency in "devDependencies" of the same name with version "^8.34.0"
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ ssr-common-utils@6.2.161
├─ ssr-core-vue3@6.2.21
├─ ssr-deepclone@1.0.1
├─ ssr-mini-css-extract-plugin@1.6.10
├─ ssr-plugin-nestjs@6.2.26
├─ ssr-plugin-vue3@6.2.119
│  └─ ssri@7.1.1
├─ ssr-serialize-javascript@6.0.4
├─ ssr-server-utils@6.2.69
├─ ssr-types@6.2.65
├─ ssr-vite-plugin-style-import@2.0.1
├─ ssr-webpack@6.2.17
├─ ssr-webpack4@4.46.2
├─ ssr-window@3.0.0
├─ ssr@6.2.82
└─ ssri@6.0.2

**Comment by zhangyuang** [comment]
默认example没有问题，可以升级typescript到5.x试试

**Comment by nead3009** [comment]
> 默认example没有问题，可以升级typescript到5.x试试

升级了问题依旧存在，还有其他方法么

**Comment by zhangyuang** [comment]
提供复现
