### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by GodLyons** [ykfe/ssr#344]
## 详细描述你的问题
我在使用nestjs-react-ssr和nestjs-react18-ssr两个脚手架中开发的时候，安装了一个依赖包@uiw/react-md-editor（安装Monaco的时候也是这样）时报错。由于一些要求我无法上传源码，但是复现非常好复现，只需要正常安装Monaco（或者那个包）都可以复现，在client打包的时候出错。我修改了服务端的配置，使用了csr的模式，所以只是client端的打包。据我观测，主要是两种错误：
1. 存在依赖包，但是提示不存在，这个不知道是不是esm的问题，我不确定
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/2ca94df6-17ed-4aeb-a512-1f2dba3883dc">

2. node_modules里面的esm文件夹下的代码，部分语法解析不了，比如 ?? 或者其他版本较高的es语法
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/8bb448aa-c296-4692-a10d-2e414b8142cf">

但是，我在使用其他脚手架的时候都可以正确下载并加载使用，我排查了半天，暂时还没搞懂为什么，也希望你可以告诉我一下原因。

## 期望的结果
第一个问题我没搞懂原因到底是为什么导致出错。
第二个问题是node_modules里面的代码语法版本过高，我难道需要再使用babel对该包进行编译吗？

## 当前使用的版本
环境描述：
nodejs：v20
脚手架：nestjs-react-ssr或者nestjs-react18-ssr
出错依赖包：@uiw/react-md-editor ，v4.0.4

## 复现仓库地址
无

**Comment by zhangyuang** [comment]
https://github.com/webpack/webpack/issues/9509

webpack4不支持识别 exports字段，可以换一个库
