### ISSUE TITLE
node-gyp grpc包编译报错，不知道是不是对应包含版本的问题

### ISSUE THREAD

**Issue by cheaprYang** [ykfe/ssr#36]
![image](https://user-images.githubusercontent.com/29188164/112717188-f7ddc400-8f25-11eb-984b-b9c768844d1c.png)

**Comment by zhangyuang** [comment]
提供环境npm 版本 node版本。

**Comment by zhangyuang** [comment]
为啥会有grpc的依赖出现呢-。-

**Comment by cheaprYang** [comment]
> 提供环境npm 版本 node版本。

npm 7.6.3   node v14.15.2

**Comment by cheaprYang** [comment]
> 为啥会有grpc的依赖出现呢-。-

这个是直接用的 https://github.com/ykfe/ssr/tree/dev/example/nestjs-vue3-ssr 这个demo版本

**Comment by zhangyuang** [comment]
无法复现。可以换成yarn和其他版本的node/npm试试

**Comment by zhangyuang** [comment]
and 你需要检查一下为什么会出现grpc。正常安装并不会安装这个依赖。建议删除lock 重新来一遍。或者是你自己装了其他的东西
![image](https://user-images.githubusercontent.com/17424434/112787680-a7807680-908b-11eb-959f-7f0f21a075ba.png)

**Comment by cheaprYang** [comment]
> and 你需要检查一下为什么会出现grpc。正常安装并不会安装这个依赖。建议删除lock 重新来一遍。或者是你自己装了其他的东西
> ![image](https://user-images.githubusercontent.com/17424434/112787680-a7807680-908b-11eb-959f-7f0f21a075ba.png)

好的 我试试
