### ISSUE TITLE
服务端的渲染过程开放勾子函数，用来实现缓存功能

### ISSUE THREAD

**Issue by asd123freedom** [ykfe/ssr#44]

**Comment by zhangyuang** [comment]
没必要啊。。本来render方法的逻辑就很简单。而且返回的是个 stream 你也缓存不了。要么你就返回 string 自己缓存。完全在外层就可以做，不需要应用开放勾子

**Comment by asd123freedom** [comment]
好的，多谢解答，我再研究下
