### ISSUE TITLE
当设置的路由是/user,浏览器输入的是/user12,body会返回一个OK，如何对这种做404处理

### ISSUE THREAD

**Issue by Ben-Ben-B** [ykfe/ssr#50]
有加中间件的，但输入/user12，和正确路由返回的都是ctx.status ===200，ctx.body===undefined
// app/middleware/notfound_handler.js
module.exports = () => {
  return async function notFoundHandler(ctx, next) {
    await next();
    if (ctx.status === 404 && !ctx.body) {
      if (ctx.acceptJSON) {
        ctx.body = { error: 'Not Found' };
      } else {
        ctx.body = '<h1>Page Not Found</h1>';
      }
    }
  };
};

**Comment by Ben-Ben-B** [comment]
使用的版本是5.5.13，@midwayjs/web是2.10.6，最新版本

**Comment by zhangyuang** [comment]
路由对不上那肯定是会404的啊。。返回ok说明对上了。那就是你自己写代码的问题

**Comment by Ben-Ben-B** [comment]
@zhangyuang 不对，现在我的问题是路由对不上没有返回404而是返回OK了，不管对不对的上都返回OK了

**Comment by zhangyuang** [comment]
那就还是你自己代码的问题啊。返回ok说明对上了。。。。

**Comment by Ben-Ben-B** [comment]
@zhangyuang 我运行的是demo代码，啥都没改，以前的版本可以的，最新的版本不行，我看看是哪个版本可以吧

**Comment by zhangyuang** [comment]
给个复现。。。

**Comment by Ben-Ben-B** [comment]
@zhangyuang 抱歉没事了，用vite开发不管走什么路由都会返回OK的，只要跑webpack就没事了，

**Comment by Ben-Ben-B** [comment]
@zhangyuang 是跑错命令，跑了ssr start --vite，跑ssr start就没事了

**Comment by zhangyuang** [comment]
你用 vite 跑也没问题啊照样写404中间件。。生产环境又没有vite。 vite返回ok是因为会对所有请求做兜底。

**Comment by Ben-Ben-B** [comment]
@zhangyuang 嗯，主要是发现中间件突然不起作用了，对比一下以前的，发现命令跑错了，现在没问题了。谢谢
