### ISSUE TITLE
nestjs-react-ssr 能支持 Serverless 形式部署吗？

### ISSUE THREAD

**Issue by baofengs** [ykfe/ssr#59]
nestjs-react-ssr 能支持 Serverless 形式部署吗？

如果想实现 nest 支持 Serverless 部署到阿里云，我们应该怎么实现？

**Comment by zhangyuang** [comment]
不支持，serverless发布能力是借助 midway 提供的能力实现

若不使用midway，需要自己手动去适配特定云平台的发布规则例如阿里云的 [fun](https://github.com/alibaba/funcraft?spm=a2c4g.11186623.2.8.16e151243xWjfD) 函数计算工具。成本过高

**Comment by zhangyuang** [comment]
问题已解决，后续将会框架层面支持服务端使用 nestjs 时的deploy功能一键发布到 serverless 平台

**Comment by zhangyuang** [comment]
close by https://github.com/ykfe/ssr/commit/705410b6b793e3516e5c5dcb650e307b5037ed12
