### ISSUE TITLE
框架有没有提供根据不同页面添加不同的meta 标签的功能

### ISSUE THREAD

**Issue by lzy2014love** [ykfe/ssr#60]

**Comment by zhangyuang** [comment]
查看文档 http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2%E6%A0%87%E9%A2%98,%20meta%20%E7%AD%89%E4%BF%A1%E6%81%AF

**Comment by Gorden-Wang** [comment]
Hi @zhangyuang 
非常感谢团队能够开源此框架，我们正在调研看从Nuxt上迁移过来，基于这个Issue我这里可能有一些补充的场景，也麻烦帮忙解惑或提供建议：

`<head>`标签中大多数可以通过`ctx`根据不同的`path`进行枚举出来，我这里有这样一种场景，需要根据`page`的接口返回的数据，添加相关seo 或 社交媒体的标签：
![image](https://user-images.githubusercontent.com/6468548/123236873-bf8f5700-d50f-11eb-91ea-4b5f872145d2.png)


![image](https://user-images.githubusercontent.com/6468548/123236477-68898200-d50f-11eb-9148-99551ccca31f.png)

这种些数据的获取来自 页面 的 fetch：
* 一种解决方案是在 layout上面去获取数据再传给页面；
* 或者有一个service来返回这些meta信息，将这个数据和页面主要数据进行分离。
感觉每种方案都有点别扭。看官方是否有一些思路或考虑加入功能的支持？

**Comment by zhangyuang** [comment]
你这种情况是要在fetch之前获取数据，把数据在服务端获取挂到ctx上在layout获取即可
建议扫码加入微信群

**Comment by zhangyuang** [comment]
@Gorden-Wang 哦不用。。你可以看看 文档 provide/inject 这个章节。在fetch里面获取后可以在props.asyncData里面拿到,不过现在只能在 `app.vue` 拿到 我需要加一下在 `layout/index.vue` 也能拿到

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/features$communication#Provide/Inject

**Comment by zhangyuang** [comment]
version@5.5.62 支持 `layout/index.vue` 通过 `props.fetchData` 拿到 layout fetch 的数据 发布中，@Gorden-Wang

**Comment by zhangyuang** [comment]
用法参考 http://doc.ssr-fc.com/docs/features$communication#props%20%E7%9B%B4%E5%87%BA%E6%95%B0%E6%8D%AE

**Comment by Gorden-Wang** [comment]
> version@5.5.62 支持 `layout/index.vue` 通过 `props.fetchData` 拿到 layout fetch 的数据 发布中，@Gorden-Wang

👍，神速。

**Comment by jarvi07** [comment]
![QQ_1723970603894](https://github.com/user-attachments/assets/c4a264f1-e5af-4a91-b0b2-163a5b120df6)
vue2 使用asyncData layout/index 可以在服务端渲染拿到，但是使用csr降级，则无法获取数据，请问vue中如何拿到，使用ctx设置可以吗
![QQ_1723970763039](https://github.com/user-attachments/assets/b2098872-e582-4263-ab52-ad78ef6d54f6)

![QQ_1723970641282](https://github.com/user-attachments/assets/4da7875a-996a-4b9a-b3a9-f494636662c0)

**Comment by zhangyuang** [comment]
> ![QQ_1723970603894](https://private-user-images.githubusercontent.com/178700850/358894193-c4a264f1-e5af-4a91-b0b2-163a5b120df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzEzODksIm5iZiI6MTcyMzk3MTA4OSwicGF0aCI6Ii8xNzg3MDA4NTAvMzU4ODk0MTkzLWM0YTI2NGYxLWU1YWYtNGE5MS1iMGIyLTE2M2E1YjEyMGRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjkxZDlkOTc0OGIxMGMzYzVhNWU3MDUxNjA3NTk1M2RhZjNiZTM3OWYyMjc5YzIxZmQwMzczM2FiODI2ZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZkzXd7bRf-gTTKhlnzV9qoW1bGC8qeWG2axZNHJTFYc) vue2 使用asyncData layout/index 可以在服务端渲染拿到，但是使用csr降级，则无法获取数据，请问vue中如何拿到，使用ctx设置可以吗 ![QQ_1723970763039](https://private-user-images.githubusercontent.com/178700850/358894302-b2098872-e582-4263-ab52-ad78ef6d54f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzEzODksIm5iZiI6MTcyMzk3MTA4OSwicGF0aCI6Ii8xNzg3MDA4NTAvMzU4ODk0MzAyLWIyMDk4ODcyLWU1ODItNDI2My1hYjUyLWFkNzhlZjZkNTRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjE0NjVkYmI1NGMwZTliZWM0ZDk2ZmI2Yzg2YWU1MjQ5NWYzMmE1OGRkYzU4MDEyNjU2MTE1MmJlMTViMjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kAOngvwi6SDz0rAjAMEO60yxyMxXxeZM_mtSuGmf3PA)
> 
> ![QQ_1723970641282](https://private-user-images.githubusercontent.com/178700850/358894214-4da7875a-996a-4b9a-b3a9-f494636662c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzEzODksIm5iZiI6MTcyMzk3MTA4OSwicGF0aCI6Ii8xNzg3MDA4NTAvMzU4ODk0MjE0LTRkYTc4NzVhLTk5NmEtNGI5YS1iM2E5LWY0OTQ2MzY2NjJjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGNjN2QzNjg1ZWEzNTZmNTg4MWU5ZWJhOGQ4ZDA5ZTZlODcwZTJhMDFlZmZlNTgyMDQ3ODM1YjRjNTBiNDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LafdIwDnnWPcfP7zOgvoIs7NtZdlA-ohZw60101VfO0)

可以，降级到csr后，fetch只会在客户端调用，在layout中仍然可以拿到当前的ctx
