### ISSUE TITLE
两个页面的fetch.ts返回数据混合

### ISSUE THREAD

**Issue by Rainer-Yu** [ykfe/ssr#64]
plugin-vue3/src/entry/client-entry.ts 
![image](https://user-images.githubusercontent.com/62528887/120141473-24a4a500-c20f-11eb-9eb7-b5bb0a1a4cfa.png)
fetch.ts 返回的数据合并进 asyncData 使用的是reactive 不必添加 .value包装 也不会丢失响应性

在 vue3当中 ref() 响应式 是带有 .value 包装的  reactive() 是通过proxy 实现的 无需 .value包装
带有 .value 还会在后续取值的操作上 重复写出 带有 .value 的代码

**Comment by zhangyuang** [comment]
那肯定是得加的啊，你除了考虑fetch.ts返回，还有直接修改asyncData的可能。如果我直接把asyncData赋值了一个新的obj，响应性就没了。如果加了.value就算你把整个.value赋值新的obj，响应性仍然存在

**Comment by zhangyuang** [comment]
ref: ![image](https://user-images.githubusercontent.com/17424434/120213616-fdc58d80-c265-11eb-971c-a90d42e45852.png)

**Comment by Rainer-Yu** [comment]
ssr-plugin-vue3\src\entry\client-entry.ts
![image](https://user-images.githubusercontent.com/62528887/120226304-86015e00-c279-11eb-8a9c-7631c810c940.png)

现在的问题是 切换页面,之前页面fetch.ts返回的数据还存在于 asyncData.value 里面,导致两个页面的fetch.ts返回数据混合,是有意这样设计 还是?
