### ISSUE TITLE
Only use vite (+ vite-plugin-ssr)?

### ISSUE THREAD

**Issue by brillout** [ykfe/ssr#65]
Hi, neat project. I like the framework-agnosticity of it.

Have you thought of going all-in with Vite instead of also supporting Webpack? This would likely simplify the stack.

I'm the author of https://github.com/brillout/vite-plugin-ssr and I designed it to be a do-one-thing-do-it-well composable tool. Maybe using vite-plugin-ssr would make your life easier?

Exicting to see the Vite ecosystem growing.

**Comment by brillout** [comment]
(Also btw I'm currently implementing the website docs for vite-plugin-ssr and I'm thinking of having the docs also in other languages.)

**Comment by zhangyuang** [comment]
Thanks for your suggestion. 
In ssr framework, we have supported use vite in ssr scene。but we don't use vite to compile all server/client code which will bring some compatible problem and i think there is no need to do so far. we only use vite compile client code in development in the present。
May be we will separate webpack/vite completely in the future and will pay attention to `vite-plugin-ssr`

**Comment by brillout** [comment]
Ok that makes sense.

Yea I believe long term removing Webpack would be good for DX. People don't have the best relationship with Webpack :-).

And if we end up collaborating that'd be great. I'm especially interested in supporting frameworks & boilerplates with vite-plugin-ssr.

**Comment by zhangyuang** [comment]
look forward to some solution 😄

**Comment by zhangyuang** [comment]
temporary close the issue, may be reopen in the future

**Comment by brillout** [comment]
👍 😊
