### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by maskTAQ** [ykfe/ssr#68]
http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%8F%AF%E8%AE%BF%E9%97%AE%E7%9A%84%E5%AF%B9%E8%B1%A1%E7%9A%84%E9%97%AE%E9%A2%98

按照文档描述的当依赖的库中引用浏览器宿主对象(document)时采用require，但是在vite编译下导致报错,webpack无此问题。
有在vite下使用require的方法吗。

**Comment by zhangyuang** [comment]
用 import 
```
 async created () {
const $ = __isBrowser__ ? await import('jquery') : {}
this.$ = $
  },
```

**Comment by maskTAQ** [comment]
```js
function(){
let $;
useEffect(async ()=>{
 $ = __isBrowser__ ? await import('jquery') : {}
});
console.log($,'$');
return null
}
```
谢谢指导。
在react中像这样吗?

**Comment by zhangyuang** [comment]
不需要，useEffect本来就只会在客户端执行

```js
let $ = {}
export default  (props: SProps) => {
  useEffect(() => {
    initJquery()
  }, [])
  const initJquery = async () =>{
    $ = await import('jquery')
  }
```

**Comment by maskTAQ** [comment]
谢谢
