### ISSUE TITLE
feat：是否支持 SSG

### ISSUE THREAD

**Issue by zhangyuang** [ykfe/ssr#75]
`SSG` 就是静态渲染，也就是预渲染。构建时生成页面 html 源码。优势就是 ssr 带来的优势只是不需要 Node.js 环境。缺点是只能渲染简单的静态界面
比较常用的场景是在纯静态展示页面例如官网博客等场景。

个人对是否支持 `SSG` 存观望态度。我认为这是一个伪需求

1、ssg 场景非常少
2、ssg 功能上完全可以被 ssr 代替
3、ssg 的构建时间略长
4、serverless 场景下拥有一个 Node.js 环境是非常容易的事情。不需要像以前一样手动购买服务器搭建环境。
5、ssg 会让数据 fetch 规范变得稍微复杂一点。ssg 场景下的 fetch 与 ssr 场景下的 fetch 不一定能共用一个方法。
6、如果开发者只是需要一个 html 文件用来做降级的话。那应该直接使用 http://doc.ssr-fc.com/docs/features$csr#%E7%8B%AC%E7%AB%8B%20html%20%E6%96%87%E4%BB%B6%E9%83%A8%E7%BD%B2

**Comment by zhangyuang** [comment]
若后来的开发者仍然有支持 `SSG` 的需求。可以回复本 `issue` ,后续将会根据人数决定是否框架原生支持。

**Comment by masx200** [comment]
支持一下，有的页面就是不会经常变化的，需要一个配置项来让某些页面提前生成

如果遇到有些需要用户登陆才能访问的资源可以使用前端获取数据的方式加上骨架屏解决

**Comment by XYjourney** [comment]
希望支持一下

**Comment by zhangyuang** [comment]
后续会考虑 先想清楚自己的目的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年11月4日 20:25
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[ykfe/ssr] feat：是否支持 SSG (#75)





 
希望支持一下
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
我们是做公共内容的，所以希望直接把页面静态化
