### ISSUE TITLE
How to set up a static folder to store files

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#84]

**Comment by zhangyuang** [comment]
看文档啊。。写得很清楚了。默认示例就包含 `build` 静态文件夹

**Comment by wuyiifan** [comment]
How to define my own routing page that is not matched？

**Comment by zhangyuang** [comment]
Please read document carefully 
http://doc.ssr-fc.com/docs/features$faq#404%20500%20%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86

**Comment by wuyiifan** [comment]
Thanks

**Comment by wuyiifan** [comment]
This redirection changes the URL address and visits a defined 404 page. Is there any way to render the page without changing the address, similar to the effect of rewrite.

**Comment by zhangyuang** [comment]
Again, read the documentation carefully

**Comment by wuyiifan** [comment]
http://127.0.0.1:3000/user/12123  the url will be redirect  http://127.0.0.1:3000/404.
I want to directly display the page not found when I visit http://127.0.0.1:3000/user/12123 instead of visiting the route /404.
I feel that this framework does not seem to support.

**Comment by zhangyuang** [comment]
你要是想保持path不变，你就在服务端render一个模版提示错误页面。不可能给你去渲染一个不存在的组件，就算指定服务端渲染哪个组件到了客户端阶段也会not match。。。。麻烦简单把文档看一遍了解下基本流程再来提问
