### ISSUE TITLE
Does the naming order of the files in the pages folder affect the order of route matching?

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#85]
When I register a /request controller, the dynamic page of /:shopname will be rendered earlier, and I register a /list to be visited first.

**Comment by zhangyuang** [comment]
The priority of front-end conventional router is random， you can control priority by yourself in service code or use declared router

**Comment by 160905** [comment]
我也遇到这个问题了

**Comment by zhangyuang** [comment]
既然有多名用户都需要这个功能，那么可以把支持约定式路由优先级的事情安排一下提上日程。有兴趣可以尝试PR

**Comment by zhangyuang** [comment]
fix by version@5.5.89 http://doc.ssr-fc.com/docs/api$config#routerPriority
