### ISSUE TITLE
[Reqeust]求支持Rax

### ISSUE THREAD

**Issue by xmsz** [ykfe/ssr#86]
背景
- 我们项目在使用Rax
- 希望可以支持 ssr+serverless

**Comment by zhangyuang** [comment]
rax自身有ssr功能，虽然做的体验没有我们这么好就是了
而且rax主要用来开发 native，降级h5不是他的主要功能。如果你本来就打算开发h5页面不建议用rax

**Comment by xmsz** [comment]
> rax自身有ssr功能，虽然做的体验没有我们这么好就是了
> 而且rax主要用来开发 native，降级h5不是他的主要功能。如果你本来就打算开发h5页面不建议用rax

好吧
