### ISSUE TITLE
删除node_modules 和 yarn.lock 后重新编译js和css文件不自动注入

### ISSUE THREAD

**Issue by 160905** [ykfe/ssr#87]
[my-links 2.zip](https://github.com/ykfe/ssr/files/6916617/my-links.2.zip)
这是复现代码
`common.less`文件编写样式不生效

**Comment by zhangyuang** [comment]
你根本就没有引入 common.less 为什么会生效。。。

**Comment by 160905** [comment]
我还以为是自动引入的。那我就close了
