### ISSUE TITLE
配置routerPriority后fetch.ts的匹配不准确

### ISSUE THREAD

**Issue by 160905** [ykfe/ssr#92]
[my-links.zip](https://github.com/ykfe/ssr/files/6950364/my-links.zip)
这是复现示例。
[http://127.0.0.1:3000/tiger](url)，这个tiger是数据库里存在的一个用户，访问这个路径时理论上应该匹配`fetch$username.ts`这个文件，结果是`reset/fetch.ts`这个文件被执行。

**Comment by zhangyuang** [comment]
`routerPriority`跟 `fetch.ts`半毛钱关系都没有。你的 `fetch$username` 和 `render$username` 应该写在 `index` 文件夹里面。还有以后给复现不要再给这种包含一堆业务代码的示例！！

**Comment by zhangyuang** [comment]
如果你要放在根目录，那么你应该把 `fetch$username` 改成 `fetch.ts`。请仔细阅读文档

http://doc.ssr-fc.com/docs/features$fetch#fetch%20%E4%B8%8E%20render%20%E5%AF%B9%E5%BA%94%E5%85%B3%E7%B3%BB
