### ISSUE TITLE
多级路由匹配问题

### ISSUE THREAD

**Issue by simuusang** [ykfe/ssr#93]
路由如下
`/webview/v1/activity/dubber`
并在 `page` 建立与之对应的文件夹
![image](https://user-images.githubusercontent.com/16282764/128626950-28e71e14-e752-4710-a285-a38a881baf8d.png)

当 `webview` 文件夹中不存在 `/webview/render.tsx` 时页面无法正常渲染，报错如下
``` nodejs
ERROR in ./web/pages/webview/render.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: ENOENT: no such file or directory, open '/Users/luowei/Workspace/alpha/web/pages/webview/render.tsx'
 @ ./build/ssr-temporary-routes.js 60:11-62:33
 @ ./node_modules/ssr-plugin-vue3/cjs/entry/client-entry.js
 @ multi ./node_modules/ssr-plugin-vue3/cjs/entry/client-entry.js
```
当 `webview` 文件夹下面存在 `render.tsx` 时页面能够正常渲染，渲染内容为 `/webview/v1/activity/dubber/render.tsx` 中的内容

**Comment by simuusang** [comment]
当目录结构如下是 路由能够正常渲染
![image](https://user-images.githubusercontent.com/16282764/128627024-83366f19-f04a-4789-8863-0dbcd66ca36f.png)

**Comment by zhangyuang** [comment]
无法复现，请确认当前使用的是最新依赖并给复现

**Comment by lowequincy** [comment]
https://github.com/lowequincy/ssr-project

**Comment by simuusang** [comment]
@zhangyuang 您好我已经将依赖升级到 5.5.98 但是还是一样有问题，复现代码在以下仓库中，你只需要删除掉 webview 文件夹里面的 render.tsx 就能复现
https://github.com/lowequincy/ssr-project

**Comment by zhangyuang** [comment]
并没有任何问题。。。你不会是启动后再把文件删除的吧。。。
and现在的开发者不知道semver版本号是用来干嘛的吗。。。为什么要把版本号写死

**Comment by simuusang** [comment]
嗯... 行吧 可能之前是我操作问题 这会又没问题了
