### ISSUE TITLE
请问我提的这个问题有什么问题？你们这个群管理为什么直接喷粪了？

### ISSUE THREAD

**Issue by wenlongkang** [ykfe/ssr#94]
![image](https://user-images.githubusercontent.com/8955753/129477552-d18abb7f-0202-45d4-991c-0162bc24a7cb.png)

**Comment by wenlongkang** [comment]
就这？

**Comment by zhangyuang** [comment]
1、指的是是你这个问题白痴
2、你后面说的话让我觉得你这个人是个白痴
3、建议有点基础的后端知识
4、连框架定位都没搞清楚就少bb，还nginx tomcat。你不会以为node nginx tomcat是干同一件事的吧
5、不建议你用本框架，block了
