### ISSUE TITLE
setStyle not work

### ISSUE THREAD

**Issue by XYjourney** [ykfe/ssr#96]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 google找答案而不是在这里。

## 详细描述你的问题
setStyle is not a function
![image](https://user-images.githubusercontent.com/18476675/129697976-3837e3cc-c04a-4481-9893-479ed4ee691e.png)
![image](https://user-images.githubusercontent.com/18476675/129698008-e9c778cf-dc31-454c-87a1-1fc1141850bb.png)
![image](https://user-images.githubusercontent.com/18476675/129698045-c2a3ff7f-1ddc-4b7c-9763-fca62e0d3db2.png)

## 当前使用的版本
5.6.5

**Comment by zhangyuang** [comment]
在具体的 function里面 加载, 文档稍后更新
```js

module.exports = {
  chainClientConfig: chain => {
  const { setStyle } = require('ssr-server-utils')
}
}

```

**Comment by XYjourney** [comment]
![image](https://user-images.githubusercontent.com/18476675/129702950-e0912678-e4e9-48b2-b371-0511b64fce3f.png)

**Comment by XYjourney** [comment]
只要用这个方法 就报一堆错 我现在想用less 或者 css 但不想用modules 有没有什么方法

**Comment by zhangyuang** [comment]
跟这个方法本身有什么关系。。。明显是你自己的代码写的有问题啊
不想用modules就直接:global
到底读了提问须知没有，就贴一张图是想要干嘛。。。

**Comment by XYjourney** [comment]
关键是当我注释后 就能通过编译
![image](https://user-images.githubusercontent.com/18476675/129706430-c2f0adf7-5225-41e1-8cdf-3c038909ee7c.png)

**Comment by XYjourney** [comment]
上面那个图不是有上下文吗 否则肯定按须知来

**Comment by zhangyuang** [comment]
试了一下那并没有任何问题。。给复现

**Comment by XYjourney** [comment]
![image](https://user-images.githubusercontent.com/18476675/129731952-fb83668a-0062-4b41-acfa-a39c3c76e769.png)
![image](https://user-images.githubusercontent.com/18476675/129731654-7353ce91-b611-4d77-a36a-fb2f1bbe486f.png)
找到问题，是因为我在config.js里自定义了一些字段，在引用时出的问题， 不过这个很容易犯错

**Comment by zhangyuang** [comment]
不要自己去读config啊，config是给框架用的。前后端业务代码都有自己的配置文件
