### ISSUE TITLE
封装一个axios能在ssr模式时同时在服务端和客户端使用

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#98]
## 详细描述你的问题

 目前服务端接口`token`校验都是在请求的`header`里面添加token参数来校验，所以在取出`token`并在`header`里设置`token` ，客户端和服务端不是完全一样。所以在设置请求config和请求拦截上做一个双端的同一。

## 期望的结果
ssr时期望有一个双端通用并且支持同一的设置和相应拦截，或者有相关的其他方案也可以提供。
## 当前使用的版本
```
"dependencies": {
    "@ant-design/icons": "^4.6.3",
    "@material-ui/icons": "^4.11.2",
    "@midwayjs/cache": "^2.12.3",
    "@midwayjs/decorator": "^2.12.3",
    "@midwayjs/hooks": "^2.3.0",
    "@midwayjs/orm": "^2.12.3",
    "@midwayjs/swagger": "^1.0.7",
    "@midwayjs/web": "^2.12.3",
    "@paypal/react-paypal-js": "^7.2.1",
    "@types/cache-manager": "^3.4.2",
    "antd": "^4.16.12",
    "axios": "^0.21.1",
    "cache-manager": "^3.4.4",
    "classnames": "^2.3.1",
    "egg": "^2.30.0",
    "egg-scripts": "^2.14.0",
    "filestack-react": "^4.0.0",
    "geoip-lite": "^1.4.2",
    "mysql": "^2.18.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-intl": "^5.20.8",
    "react-loadable": "^5.5.0",
    "react-quill": "^1.3.5",
    "react-router-dom": "^5.2.0",
    "serialize-javascript": "^6.0.0",
    "ssr-core-react": "^5.6.5",
    "ssr-types-react": "^5.6.4",
    "swagger-ui-dist": "^4.0.0-beta.4"
  }
```

**Comment by zhangyuang** [comment]
那你自己封一个就几行代码。这种东西都是业务强相关的每个业务的参数都不同，框架不可能也没必要去帮你封一个这个。从来不做这种过度设计的事情

**Comment by li9269391** [comment]
同问有什么方案吗，双端有点割裂， @midwayjs/axios  + axios ？

**Comment by zhangyuang** [comment]
为什么要用midway/axios，统一用axios啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 后浪 ***@***.***&gt;
发送时间: 2021年12月19日 14:27
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 封装一个axios能在ssr模式时同时在服务端和客户端使用 (#98)





 
同问有什么方案吗，双端有点割裂， @midwayjs/axios  + axios ？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by li9269391** [comment]
明白了，谢谢
