### ISSUE TITLE
npm run deploy 到阿里云FC平台使用 Serverless-Devs 工具

### ISSUE THREAD

**Issue by rsonghuster** [ykfe/ssr#99]
## 问题
这个 ssr 很赞， 但是有一点， npm run deploy， 使用的还是  funcraft 工具， 您这边能帮忙改造下， 改成  https://github.com/devsapp/fc/tree/main/docs  使用 Serverless-Devs 工具， 这个工具会强大很多， 也是后期重点发展的， funcraft 目前处于维护阶段

## 期望的结果

 npm run deploy 默认使用的是 Serverless-Devs  去部署

**Comment by zhangyuang** [comment]
这个底层在midway场景直接调用的是 [midway](https://midwayjs.org/)
提供的发布能力。要改的话得它来改。如果要用 serverless 大部分情况下推荐用midway作为服务端框架

在nestjs 场景下是直接调用的 fun。但是这个场景不常用
